### ISSUE TITLE
Mulriple Odoo Containers with common database. 

### ISSUE THREAD

**Issue by cosmo83** [bitnami/bitnami-docker-odoo#100]
Iam trying to use the bitnami helm chart, and when iam setting the replicaCount > 1, iam having issues with the other containers crashing. I already have rwx mode on my volumes

![image](https://user-images.githubusercontent.com/973160/125882068-77eee218-8c0d-41cf-8c20-3ec970ff5f2c.png)

Odoo Docker Version: 13-debian-10

**Comment by javsalgar** [comment]
Hi,

Could you launch the chart with `image.debug=true`. It may provide more information.

**Comment by cosmo83** [comment]
odoo 09:18:06.54 INFO  ==> Updating modules                                                                                                                                               │
│ 2021-07-16 09:18:09,007 95 INFO ? odoo: Odoo version 13.0-20210710                                                                                                                        │
│ 2021-07-16 09:18:09,007 95 INFO ? odoo: Using configuration file at /opt/bitnami/odoo/conf/odoo.conf                                                                                      │
│ 2021-07-16 09:18:09,008 95 INFO ? odoo: addons paths: ['/opt/bitnami/odoo/lib/odoo-13.0.post20210710-py3.8.egg/odoo/addons', '/bitnami/odoo/data/addons/13.0', '/bitnami/odoo/addons']    │
│ 2021-07-16 09:18:09,008 95 INFO ? odoo: database: bn_odoo@odoo-postgresql:5432                                                                                                            │
│ 2021-07-16 09:18:09,512 95 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf                                                │
│ 2021-07-16 09:18:48,688 95 ERROR bitnami_odoo odoo.sql_db: bad query: update ir_module_module set state='to upgrade' where name='base' and state='installed'                              │
│ ERROR: could not serialize access due to concurrent update                                                                                                                                │
│                                                                                                                                                                                           │
│ 2021-07-16 09:18:48,698 95 WARNING bitnami_odoo odoo.modules.loading: Transient module states were reset                                                                                  │
│ 2021-07-16 09:18:48,710 95 ERROR bitnami_odoo odoo.modules.registry: Failed to load registry                                                                                              │
│ Traceback (most recent call last):                                                                                                                                                        │
│   File "/opt/bitnami/odoo/lib/odoo-13.0.post20210710-py3.8.egg/odoo/modules/registry.py", line 86, in new                                                                                 │
│     odoo.modules.load_modules(registry._db, force_demo, status, update_module)                                                                                                            │
│   File "/opt/bitnami/odoo/lib/odoo-13.0.post20210710-py3.8.egg/odoo/modules/loading.py", line 350, in load_modules                                                                        │
│     cr.execute("update ir_module_module set state=%s where name=%s and state=%s", ('to upgrade', 'base', 'installed'))                                                                    │
│   File "/opt/bitnami/odoo/lib/odoo-13.0.post20210710-py3.8.egg/odoo/sql_db.py", line 173, in wrapper                                                                                      │
│     return f(self, *args, **kwargs)                                                                                                                                                       │
│   File "/opt/bitnami/odoo/lib/odoo-13.0.post20210710-py3.8.egg/odoo/sql_db.py", line 250, in execute                                                                                      │
│     res = self._obj.execute(query, params)                                                                                                                                                │
│ psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update                                                                                                 │
│ 2021-07-16 09:18:48,717 95 CRITICAL bitnami_odoo odoo.service.server: Failed to initialize database `bitnami_odoo`.                                                                       │
│ Traceback (most recent call last):                                                                                                                                                        │
│   File "/opt/bitnami/odoo/lib/odoo-13.0.post20210710-py3.8.egg/odoo/service/server.py", line 1192, in preload_registries                                                                  │
│     registry = Registry.new(dbname, update_module=update_module)                                                                                                                          │
│   File "/opt/bitnami/odoo/lib/odoo-13.0.post20210710-py3.8.egg/odoo/modules/registry.py", line 86, in new                                                                                 │
│     odoo.modules.load_modules(registry._db, force_demo, status, update_module)                                                                                                            │
│   File "/opt/bitnami/odoo/lib/odoo-13.0.post20210710-py3.8.egg/odoo/modules/loading.py", line 350, in load_modules                                                                        │
│     cr.execute("update ir_module_module set state=%s where name=%s and state=%s", ('to upgrade', 'base', 'installed'))                                                                    │
│   File "/opt/bitnami/odoo/lib/odoo-13.0.post20210710-py3.8.egg/odoo/sql_db.py", line 173, in wrapper                                                                                      │
│     return f(self, *args, **kwargs)                                                                                                                                                       │
│   File "/opt/bitnami/odoo/lib/odoo-13.0.post20210710-py3.8.egg/odoo/sql_db.py", line 250, in execute                                                                                      │
│     res = self._obj.execute(query, params)                                                                                                                                                │
│ psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update                                                                                                 │
│ 2021-07-16 09:18:48,721 95 INFO bitnami_odoo odoo.service.server: Initiating shutdown                                                                                                     │
│ 2021-07-16 09:18:48,721 95 INFO bitnami_odoo odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.                                                         │
│ stream closed

**Comment by javsalgar** [comment]
Hi,

So it seems that it won't work as expected with several nodes because of this

```
│ psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update │
```

Potentially, it could be possible to find a workaround on this, for example only running the module updates in one of the nodes. However, I'm concerned that it could cause other unexpected issues. I will open a task for investigating this, though I will not be able to provide an ETA. However, as soon as there are more news, I will update the ticket.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-odoo#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
