### ISSUE TITLE
Upgrade to 15 Fails

### ISSUE THREAD

**Issue by Blackclaws** [bitnami/bitnami-docker-odoo#111]
**Description**
Upgrading the database fails. The issue after enabling BITNAMI_DEBUG is:
```
2021-11-04 16:51:25,681 106 ERROR bitnami_odoo odoo.sql_db: bad query: INSERT INTO "ir_config_parameter" ("id", "create_date", "create_uid", "key", "value", "write_date", "write_uid") VALUES (nextval('ir_config_parameter_id_seq'), '2021-11-04 16:51:21.844372', 1, 'mail.catchall.alias', 'catchall', '2021-11-04 16:51:21.844372', 1) RETURNING id
ERROR: duplicate key value violates unique constraint "ir_config_parameter_key_uniq"
```

If you clear that error there are multiple more later on leading to a completely broken setup
**Steps to reproduce the issue:**

1. Install V14
2. Work with it a bit, enable modules etc.
3. Upgrade to V15
4. Issue appears

**Describe the results you received:**

Odoo 15 Fails to launch due to module upgrade failures

**Describe the results you expected:**

Odoo 15 Upgrade succeeds

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Running this using the Bitnami Helm Chart Version 20

**Comment by miguelaeh** [comment]
Hi @Blackclaws ,
You are trying to upgrade between two major versions, which is expected to not work. You should follow the Odoo upgrade instructions from their docs in order to upgrade between two major versions.

**Comment by Blackclaws** [comment]
That is strange. For any other piece of software I know upgrades like this happen automatically. 

I've looked it up and it seems upgrades are "officially" only supported for enterprise customers. Anyone else has to use OpenUpgrade.

I think you should probably implement a safeguard in your images (or at least put a warning), that this is an unsupported use case and prevent the start in such a case (maybe with a file that has the last run version number in it and is checked against the image version). Especially since the section about: Upgrading this image in the docs says nothing about this being a problem, while actually doing this (or running just with the latest tag) WILL break your database in a way that is unrecoverable, at least in an  easy way.

Its not even possible to go back to the old major version.

The output when not running in debug mode is also less than helpful unfortunately.

**Comment by miguelaeh** [comment]
Hi @Blackclaws ,
Our images versions use the same name as the target application.
Maybe we have taken it for granted that image users will understand that upgrading between major versions is not something out of the box.
For applications using semver, an upgrade between major versions is not guaranteed to work, which is the case of Odoo.

**Comment by Blackclaws** [comment]
I think there are two things that aren't entirely clear. 

1. That this application is even using semver. I don't take it for granted that most applications use semver at all outside the javascript ecosystem, its starting to be more and more adopted but definitely not something I would apply to any application.
2. That image upgrades even between major versions wouldn't work out of the box even if semver applies. This is really the first application I have deployed that had this issue (nextcloud, gitlab, mattermost, keycloak, etc. even the bitnami postgresql chart work with major upgrades) . Even if semver does mean that there are breaking changes a migration script is usually bundled with the application. It seems that Odoo is not interested in providing this to their non-enterprise customers. Nothing you can do about that, but a warning would be nice as its definitely not the expected default.

**Comment by miguelaeh** [comment]
Hi @Blackclaws ,
About 1, it is not something we apply, but something Odoo does. Upgrading from `14` to `15` is major upgrade so we cannot do anything there since it comes from Odoo itself.
About 2, they have an upgrade guide at https://www.odoo.com/documentation/15.0/administration/upgrade/process.html

Our containers publish the lastest version for each branch, but we don't provide the upgrade scripts, it is in the hands of the user to follow the upstream guide for upgrading, specially between major versions.

**Comment by Blackclaws** [comment]
I totally agree that it isn't your responsibility to actually provide the upgrades. I just think a warning that major upgrades ARE breaking changes for this software without automatic upgrades (that even break an existing database so much that it won't even run for the old major version anymore) would help.

I totally accept that I should have looked into the policy of odoo for how they handle upgrades. Its just that I never had a software that bricked itself on a major upgrade without warning (and apparently does this as a default).

You should also change the readme on this image to not just recommend using tagged versions but to say that its pretty much mandatory. If you use latest you just get the major upgrade. Which in this case also bricks users as soon as latest jumps from 14 to 15.

If you'd like I can whip up an addition to the startup script that would actually check whether a major version bump has occurred and print a nice warning message in the container logs that instructs users to accept the major upgrade by setting either an environment variable or deleting/creating a file in the persistent data storage. That way you prevent users from inadvertently upgrading between major versions.

**Comment by miguelaeh** [comment]
Hi @Blackclaws ,
I am not sure that the functionality you propose will introduce more headaches than a benefit. Feel free to open a PR adding whatever you consider necessary to README.
