### ISSUE TITLE
Shared postgres container with consul connect

### ISSUE THREAD

**Issue by fred-gb** [bitnami/bitnami-docker-odoo#114]
Hello!

**Description**

Odoo containers cannot connect to postgres shared container

**Steps to reproduce the issue:**

Use Nomad/Consul/Vault 
Consul Mesh proxy with postgres container

**Describe the results you received:**

Odoo container cannot connect to database
```
odoo 10:22:46.94 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
odoo 10:22:46.95 INFO  ==> Trying to connect to the database server
odoo 10:23:47.24 ERROR ==> Could not connect to the database server
```

**Describe the results you expected:**

Odoo container connect to database shared with other apps

**Additional information you deem important (e.g. issue happens only occasionally):**

I can connect to postgres container with other testing container.
I think I don't understand the env variables.

I used ansible to deploy nomad job.

This is my file.env:

```
ODOO_DATABASE_HOST = 127.0.0.1
ODOO_DATABASE_PORT_NUMBER = 5432
ODOO_DATABASE_ADMIN_USER = {{ postgres_user.value }} 
ODOO_DATABASE_ADMIN_PASSWORD = {{ postgres_user_password.value }}
ALLOW_EMPTY_PASSWORD=no
POSTGRESQL_CLIENT_DATABASE_HOST = 127.0.0.1
POSTGRESQL_CLIENT_DATABASE_PORT_NUMBER = 5432
POSTGRESQL_CLIENT_POSTGRES_USER = postgres
POSTGRESQL_CLIENT_POSTGRES_PASSWORD = {{ postgres_password.value }} 
POSTGRESQL_CLIENT_CREATE_DATABASE_NAME = {{ postgres_database.value }} 
POSTGRESQL_CLIENT_CREATE_DATABASE_USER = {{ postgres_user.value }} 
POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD = {{ postgres_user_password.value }} 
```

postgres_password.value : **RETRIEVE-FROM-VAULT**
postgres_database.value: **odoo-domain-tld**
postgres_user.value : **odoo-domain-tld**
postgres_user_password: **GENERATE-BY-VAULT**

Does POSTGRESQL_CLIENT_* vars start before to create user, database etc. ? And after ODOO_DATABSE_* vars are used to initialise first launch of odoo?

I don't have enough time to try `psql` command from container odoo, it restarts in loop.

Certainly I forgot something or misunderstoold, what?

Thanks !

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-odoo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by fred-gb** [comment]
I got back to official odoo image and used a dedicated postgres container. 
I don't think it was a beautiful solution to preserve ressources... But It's the only solution at this time for me.
Thanks
