### ISSUE TITLE
grep: /opt/bitnami/odoo/conf/odoo.conf: No such file or directory 

### ISSUE THREAD

**Issue by riddktv** [bitnami/bitnami-docker-odoo#116]
### Name and Version

bitnami/odoo:15

### What steps will reproduce the bug?

Helm install with pvc will have:

```
odoo 08:40:02.18 Welcome to the Bitnami odoo container
odoo 08:40:02.19 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-odoo
odoo 08:40:02.20 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-odoo/issues
odoo 08:40:02.20 
odoo 08:40:02.23 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
odoo 08:40:02.29 INFO  ==> Trying to connect to the database server
odoo 08:40:02.34 INFO  ==> Creating database user arevo
odoo 08:40:02.43 INFO  ==> Creating database odoo
odoo 08:40:02.74 INFO  ==> Restoring persisted Odoo installation
odoo 08:40:02.90 INFO  ==> Trying to connect to the database server
grep: /opt/bitnami/odoo/conf/odoo.conf: No such file or directory
```

if install not mount pvc it will normally.

### What do you see instead?

helm install without pvc but it not best practises

```
odoo 08:56:40.27 Welcome to the Bitnami odoo container
odoo 08:56:40.27 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-odoo
odoo 08:56:40.27 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-odoo/issues
odoo 08:56:40.28 
odoo 08:56:40.29 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
odoo 08:56:40.30 INFO  ==> Trying to connect to the database server
odoo 08:56:40.31 INFO  ==> Creating database user arevo
odoo 08:56:40.34 INFO  ==> Creating database odoo
odoo 08:56:40.43 INFO  ==> Ensuring Odoo directories exist
odoo 08:56:40.44 INFO  ==> Trying to connect to the database server
odoo 08:56:40.46 INFO  ==> Validating database owner
odoo 08:56:40.54 INFO  ==> Generating configuration file
odoo 08:56:40.54 INFO  ==> Configuring SMTP
odoo 08:56:40.58 INFO  ==> Installing modules
```

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-odoo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by rmazzine** [comment]
In my case, this problem was related to this: https://stackoverflow.com/questions/69405454/bitnami-odoo-addons-over-init-container-not-work 

I tried to deploy odoo in a persistent volume that had some old configuration files from a latter installation. Then, removing the files from the Persistent Volume or creating a new one solved my problem.
