### ISSUE TITLE
Running container with odoo user

### ISSUE THREAD

**Issue by ruddy32** [bitnami/bitnami-docker-odoo#118]
### Name and Version

bitnami/bitnami-docker-odoo:15.0.20220410-debian-10-r0

### What steps will reproduce the bug?

Deploy odoo on kubernetes using odoo bitnami helm chart and activating security rules.
Odoo helm chart spécific values :
```
odoo:
  image:
    debug: true
  persistence:
    enabled: true
    size: 1Gi
  podSecurityContext:
    enabled: true
    fsGroup: 999
  containerSecurityContext:
    enabled: true
    runAsUser: 999
  postgresql:
    primary:
      persistence:
        enabled: true
        size: 1Gi
      podSecurityContext:
        enabled: true
      containerSecurityContext:
        enabled: true
  volumePermissions:
    enabled: true
    containerSecurityContext:
      enabled: true
  ingress:
    tls: true
    selfSigned: true
  livenessProbe:
    initialDelaySeconds: 240
    periodSeconds: 50
    timeoutSeconds: 30
  readinessProbe:
    initialDelaySeconds: 120
    periodSeconds: 40
    timeoutSeconds: 20
```

### What is the expected behavior?

Configure Odoo and its dedicated data ditectory (`/bitnami/odoo`), 
cleanup Odoo useless data (`/opt/bitnami/odoo`), 
and then start Odoo web application.

### What do you see instead?

Fail to cleanup Odoo home directory data
```
odoo 18:59:55.18 INFO  ==> Updating admin user credentials
UPDATE 1
odoo 18:59:55.23 INFO  ==> Persisting Odoo installation
rm: cannot remove '/opt/bitnami/odoo/addons': Permission denied
```

### Additional information

Odoo data directory (`/bitnami/odoo`) status after pod init-container phase
```
volume-permissions drwxrwsr-x 3 root odoo 4.0K May 10 18:57 .
volume-permissions drwxr-xr-x 3 root root 4.0K Apr 10 13:29 ..
volume-permissions drwxrws--- 2 root odoo  16K May 10 18:57 lost+found
```
Odoo home directory (`/opt/bitnami/odoo`) status after pod init-container phase
```
volume-permissions drwxr-xr-x  1 root root 4.0K Apr 10 13:29 .
volume-permissions drwxrwxr-x  1 root root 4.0K Apr 10 13:27 ..
volume-permissions drwxrwxr-x  2 odoo root 4.0K Apr 10 13:29 addons
volume-permissions drwxr-xr-x  1 root root 4.0K Apr 10 13:29 bin
volume-permissions drwxrwxr-x  2 odoo root 4.0K Apr 10 13:29 conf
volume-permissions drwxrwxr-x  2 odoo root 4.0K Apr 10 13:29 data
volume-permissions drwxr-xr-x  4 root root 4.0K Apr 10 12:39 lib
volume-permissions drwxr-xr-x  2 root root 4.0K Apr 10 12:39 licenses
volume-permissions drwxrwxr-x  2 odoo root 4.0K Apr 10 13:29 log
volume-permissions drwxr-xr-x 28 root root 4.0K Apr 10 12:39 node_modules
volume-permissions drwxr-xr-x  2 root root 4.0K Apr 10 13:29 odoo
volume-permissions -rw-r--r--  1 root root 7.4K Apr 10 12:18 package-lock.json
volume-permissions drwxrwxr-x  3 odoo root 4.0K Apr 10 13:29 tmp
volume-permissions drwxr-xr-x  5 root root 4.0K Apr 10 12:39 venv
```
Odoo process, started with `odoo` system user, should be able to delete `/opt/bitnami/odoo/addons` (odoo is the owner).
Even if Odoo init process create some items in this folder, `odoo` system user should be the owner.
There is no problem using root user instead of odoo user.
What's going wrong ? Is there specific option for this use case ?

**Comment by javsalgar** [comment]
Hi,

Please, note this container and helm chart is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version.

**Comment by ruddy32** [comment]
Hi,

Odoo package is deployed using root account. This makes `/opt/bitnami/odoo` folder owned by root.

I guess the best option is to update **ODOO_BASE_DIR** settings by settings **ODOO_DAEMON_USER** as the owner of the directory. This will allow **restore_persisted_app** method to replace `/op/bitnami/odoo` addons directory by a symbolic link. This can be done in the **postunpack.sh** script

Is it the right way to do ?

Thanks
