### ISSUE TITLE
How can use external postgress ?

### ISSUE THREAD

**Issue by esakarya** [bitnami/bitnami-docker-odoo#123]
### Name and Version

bitnami/odoo:15

### What steps will reproduce the bug?

How can i use this image with external postgresql ? and disable postgresql installation automatically.

also any possiblities change odoo addons ?

### What do you see instead?

How can i use this image with external postgresql ? and disable postgresql installation automatically.

also any possiblities change odoo addons ?

**Comment by javsalgar** [comment]
Hi,

Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.
