### ISSUE TITLE
Customzing sales Analysis using two table is it posiible in odoo 8 and 9?

### ISSUE THREAD

**Issue by LakshminarayananOKN** [bitnami/bitnami-docker-odoo#17]
In graph and pivot table view, x axis one table. y-axis another one table is this possible to show our data for analytical view if it possible give me some some example of using two tables as x and y axis how to customize, if not possible to use two table in x,y axis, why give me some pretty simple example for both of question?

thanks for your attention......!

**Comment by jloramas** [comment]
I think it will be better for you to ask functional questions in the Odoo forums. Doing  a quick google search I found this one: https://www.odoo.com/forum/help-1

Hope it helps.
