### ISSUE TITLE
general setup issues/questions

### ISSUE THREAD

**Issue by BrentDietrich** [bitnami/bitnami-docker-odoo#40]
I apologize in advance, but my knowledge of docker and odoo is very new and therefore limited.

Quick note, when I run the following curl cmd: 
`curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-odd/master/docker-compose.yml`
The file only contains `404: Not Found`

When I run `docker-compose up`, the odoo container exits with the following:
`odoo_1        | Error executing 'postInstallation': User bn_odoo already exists`

### Is this expected?

**Docker Version**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

- Output of `docker info`:

```
Containers: 22
 Running: 0
 Paused: 0
 Stopped: 22
Images: 44
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 307
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.13-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: KVCR:NLJJ:GPV4:LZLH:DTZF:TFOR:62ZQ:2V5X:PML7:QHL5:4YBA:JPM3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2017-05-03T18:27:06.675721365Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` :

```
docker-compose version 1.11.2, build dfed245
```

**Comment by carrodher** [comment]
Hi @BrentDietrich,

Thanks for reported it. The issue related with 
```
curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-odd/master/docker-compose.yml
``` 
was due to a typo in the README, I just fixed it in the commit https://github.com/bitnami/bitnami-docker-odoo/commit/d826e61d246545559d608e85510b7bee1ff3263e

You can execute these commands (both in the same directory):
```
curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-odd/master/docker-compose.yml
docker-compose up
```
These commands have worked without problem for me.

If your problem persists, I recommend you to try a "clean installation". You should stop and remove containers and volumes (at least those related to Odoo). You should execute `docker ps -a` to identify the `CONTAINER_ID` of the containers related with Odoo (`bitnami/odoo` and `bitnami/postgresql`), after that, you can run:
```
docker stop ODOO_CONTAINER_ID POSTGRESQL_CONTAINER_ID
docker rm ODOO_CONTAINER_ID POSTGRESQL_CONTAINER_ID
docker volume rm bitnami_postgresql_data bitnami_odoo_data
```

Best regards

**Comment by BrentDietrich** [comment]
Thanks for the info and sorry for delayed response. It turns out it was a conflict with a previous install.
