### ISSUE TITLE
Database backup error: Command `pg_dump` not found.

### ISSUE THREAD

**Issue by benoitlavorata** [bitnami/bitnami-docker-odoo#42]
Dear Bitnami Team,

First, thank you for your hardwork, big fan here.

**Description**
On a brand new install of bitnami/odoo:latest with bitnami/postgresql:latest, I try to backup the default database "bitnami_odoo".
But it does not seems to work.

**Steps to reproduce the issue:**

1. Yhe docker-compose.yml file
```yml
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_PASSWORD=odoo11
  odoo:
    image: 'bitnami/odoo:latest'
    ports:
      - '8069:8069'
      - '8071:8071'
    depends_on:
      - postgresql
    environment:
      - ODOO_EMAIL=admin
      - ODOO_PASSWORD=1234
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=odoo11
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT_NUMBER=5432
```
2. execute docker-compose up in the same folder as the yml file, everything starts properly, I can access the odoo install, create/duplicate/delete database if wanted.

3. Click on Backup database (tried both with dump only or with filestore)

4. The issue occurs

**Describe the results you received:**

On the web interface I get this:
```
Database backup error: Command `pg_dump` not found.
```

In the log of Odoo container, I get this:
```log
odoo_1        | 2018-01-19 01:54:35,738 51 INFO bitnami_odoo odoo.service.db: DUMP DB: bitnami_odoo format zip
odoo_1        | 2018-01-19 01:54:35,854 51 ERROR bitnami_odoo odoo.addons.web.controllers.main: Database.backup
odoo_1        | Traceback (most recent call last):
odoo_1        |   File "/opt/bitnami/odoo/odoo/tools/misc.py", line 94, in find_pg_tool
odoo_1        |     return which(name, path=path)
odoo_1        |   File "/opt/bitnami/odoo/odoo/tools/which.py", line 144, in which
odoo_1        |     raise IOError(ENOENT, '%s not found' % (mode & X_OK and 'command' or 'file'), file)
odoo_1        | FileNotFoundError: [Errno 2] command not found: 'pg_dump'
odoo_1        | 
odoo_1        | During handling of the above exception, another exception occurred:
odoo_1        | 
odoo_1        | Traceback (most recent call last):
odoo_1        |   File "/opt/bitnami/odoo/odoo/addons/web/controllers/main.py", line 732, in backup
odoo_1        |     dump_stream = odoo.service.db.dump_db(name, None, backup_format)
odoo_1        |   File "", line 2, in dump_db
odoo_1        |   File "/opt/bitnami/odoo/odoo/service/db.py", line 40, in if_db_mgt_enabled
odoo_1        |     return method(self, *args, **kwargs)
odoo_1        |   File "/opt/bitnami/odoo/odoo/service/db.py", line 216, in dump_db
odoo_1        |     odoo.tools.exec_pg_command(*cmd)
odoo_1        |   File "/opt/bitnami/odoo/odoo/tools/misc.py", line 122, in exec_pg_command
odoo_1        |     prog = find_pg_tool(name)
odoo_1        |   File "/opt/bitnami/odoo/odoo/tools/misc.py", line 96, in find_pg_tool
odoo_1        |     raise Exception('Command `%s` not found.' % name)
odoo_1        | Exception: Command `pg_dump` not found.
```

**Describe the results you expected:**

I expected to download the zip file. 

**Additional information you deem important (e.g. issue happens only occasionally):**

I checked on the official odoo container, it seems they recommend using postgresql:9.4, and they ship some tools of postgresql in their odoo container to be able to execute the dumps.

I tried with the vanilla odoo:11.0 (official) and postgresql:9.4 => it works indeed.

**Version**

- Output of `docker version`:

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

- Output of `docker info`:

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 72
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: L5C2:6HHL:SPYT:UNSX:TP6Z:YJAK:QXMW:V2NO:VP3A:MN35:IN5J:KGIG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3128
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

I am using Docker for MAC, my OS information are below:
```
 System Version:	macOS 10.13.2 (17C88)
  Kernel Version:	Darwin 17.3.0
```

Do you have a workaround to be able to perform these tasks ?

Thank you in advance,
Benoit Lavorata.

**Comment by juan131** [comment]
Hi @sbglive 

According to Odoo developers it supports PostgreSQL 10: https://github.com/odoo/odoo/issues/19924

> we do support it officially as well, now that it is released.

Regarding the error you're facing the problem is that we're not including the `pg_dump` tool on the Odoo image. We're just including the client as you can check by running the command:

```
docker-compose exec odoo ls /opt/bitnami/postgresql/bin/
```

However, you can easily create a dump of your database by running:

```
docker-compose exec postgresql pg_dump -U postgres bitnami_odoo > backup.sql
```

The PostgreSQL docker images includes the tool and the database is named `bitnami_odoo` so it's easy to dump it.

**Comment by sbglive** [comment]
Dear Juan,

I understand your point and knew I could do it manually :)

This being said, it means that the current setup break a convenient feature of the standard Odoo install: restoring/dumping the database with a few clicks from a web page.

If I want to fix this issue, then I should add the missing binaries (pg_dump) in /opt/bitnami/postgresql/bin/ ?

Thank you for your reply,
Benoit.

**Comment by juan131** [comment]
Hi @sbglive 

I agree with you! It affects a basic feature on the Odoo admin dashboard. I'll open an internal task to add the missing binaries to `/opt/bitnami/postgresql/bin/`. Thanks so much for reporting it.

**Comment by marcosbc** [comment]
Hi,

We released a new revision of the Bitnami Odoo container, which includes the pg_dump and pg_restore binaries.

Please let us know if it works for you.

**Comment by C-Fu** [comment]
I just downloaded a fresh new latest docker image of bitnami's postgres and odoo image, and it didn't work.

**Comment by marcosbc** [comment]
@C-Fu Are you finding the same issue?

Note that you need to remove your old container image before downloading it again (unless you pull it):

    $ docker rmi bitnami/odoo:latest
    $ docker-compose up

We weren't able to find any issues, using the `bitnami/odoo:latest` Docker container. We are able to download backup files in the Database Manager before logging in. Also, we used the docker-compose file mentioned in this case.

If you are still finding issues, could you provide more details about it?
