### ISSUE TITLE
post nami-initialization customization of odoo-server.conf

### ISSUE THREAD

**Issue by bradrust** [bitnami/bitnami-docker-odoo#44]
**Description**

Currently using the kubernetes helm chart for odoo bootstrapping into a google cloud cluster. This uses the bitnami odoo docker image (v11) for the main odoo content.

When a new instance is created, bitnami has some configuration magic which I assume is done through the /app-entrypoint.sh via "nami_initialize odoo". I assume this is where the odoo-server.conf is created based on docker ENV variables (e.g., POSTGRESQL_HOST)

I have a modified Dockerfile with some extras (e.g., installing "vi" to edit files, postgres-9.6 for pg_dump, etc...). Since I am managing my own Dockerfile (which I 'git pull' from here) which I build an image with "docker build ."    Bitnami forum suggested I submit an issue here for a feature request.

Is there a way to include some post nami initialize odoo customizations?   Mainly I want to change/add-to the odoo-server.conf.  I realize that I can edit that file myself but I am looking for some additional initialization hooks to further assist with automation of installation.

**Steps to reproduce the issue:**

1. helm install odoo
2. running instance has a generated (not sure when this happens) /opt/bitnami/odoo/odoo-server.conf
3. requirement to edit odoo-server.conf && nami restart odoo

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

bitnami odoo version
```
odoo-11.0.20180115-0
```

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.11-gke.1", GitCommit:"3500f53730c1fea7b57901977df165c3eb317bce", GitTreeState:"clean", BuildDate:"2017-12-08T18:05:07Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @bradrust 

> When a new instance is created, bitnami has some configuration magic which I assume is done through the /app-entrypoint.sh via "nami_initialize odoo". I assume this is where the odoo-server.conf is created based on docker ENV variables (e.g., POSTGRESQL_HOST)

Yes, the Odoo Nami module's logic is the one that creates the configuration file `odoo-server.conf`. You can find the Nami modules' logic at `root/.nami/components/com.bitnami.odoo/` within the container.

> Is there a way to include some post nami initialize odoo customizations? Mainly I want to change/add-to the odoo-server.conf. I realize that I can edit that file myself but I am looking for some additional initialization hooks to further assist with automation of installation.

Yes, as you mentioned you can edit the `app-entrypoint.sh` file so you deploy extra-changes on the configuration file. Please note that you need to restart Odoo once you modify the configuration file, so do not forget to add a `nami restart odoo` action.

**Comment by bradrust** [comment]
Thanks very much for that info.  I plan on injecting some information into the /root/.nami/components/com.bitnami.odoo/templates/odoo-server.conf.tpl template.  

I see the ".initialized" file as a state designator.   Could you comment on the "$1" passed to app-entrypoint.sh?   Not sure when ("$1" == "/init.sh").   It seems like the docker entrypoint would always be the same which would further explain the use of the ".initialized" state holder. 

Are there any bitnami public docs that might explain a bit of the nami components and the lifecycle of templates, or entry points into those utilities?  

Otherwise, thanks a lot for the help.  Very nice and clean approach to componentizing all of these moving parts.

**Comment by juan131** [comment]
> Are there any bitnami public docs that might explain a bit of the nami components and the lifecycle of templates, or entry points into those utilities?

You can find information in the GH repo: https://github.com/bitnami/nami

The **.initialized** is used by the Odoo Nami module logic so it deploys different actions when initialising the container depending on whether the container was previously initialised (you're simply restarting the container) or not. For instance, you don't need to populate the database if you're restarting you container.

The problem about modifying `/root/.nami/components/com.bitnami.odoo/templates/odoo-server.conf.tpl` is that you won't be able to reuse that information if you update the image since the Odoo nami module is downloaded and unpacked while building the Docker image so the template will be substituted by the default one.

That's why I recommend you to edit the `app-entrypoint.sh` so you add lines to the config file instead.

**Comment by gridworkz** [comment]
Would it be possible to do a git pull in app-entrypoint.sh to grab some addons and add them to the pod when it's being created? Would the /opt/bitnami/odoo/data/addons/12.0 directory be available at this point?

**Comment by juan131** [comment]
Hi @gridworkz 

I noticed you also commented on this [other issue](https://github.com/bitnami/bitnami-docker-odoo/issues/68). I'll continue the discussion there.
