### ISSUE TITLE
SMTP : Connection test failed!  5.7.8 Error

### ISSUE THREAD

**Issue by Tofdu31** [bitnami/bitnami-docker-odoo#46]
**Outgoing SMTP**

Authentication error on outgoing mail server:
5.7.8 Error: authentication failed.

**Steps to reproduce the issue:**

1. [First Step]
I configured my docker-compose.yml and it does not work:
    environment:
      - SMTP_HOST=SSL0.OVH.NET  
      - SMTP_PORT=465
      - SMTP_USER=serveur@nbility.fr  
      - SMTP_PASSWORD=mypassword

I find it abnormal that we can not inform to use the security of the connection: SSL / TLS

2. [Second Step]
I wanted to test with the odoo administration interface:
Here is the information I put:
Description: SSL0.OVH.NET-SORTANT
Priority : 10
SMTP server: SSL0.OVH.NET
SMTP Port: 465

Security and Authentication
Security of the connection: SSL / TLS
Username: serveur@nbility.fr
Password: mypassword

**Describe the results you received:**

I still have the error

Connection test failed! Here's what we have instead:
535
5.7.8 Error: authentication failed: UGFzc3dvcmQ66

**Describe the results you expected:**

I do not know why I have this error. The information is good since I use it on another server (bitnami / nextcloud)

**DOCKER-COMPOSE.YML**
Here is my docker-compose.yml that I set up:

`version: '2'

networks:
  network_odoo:
    driver: bridge

services:

  postgresql:
    image: 'bitnami/postgresql:latest'
    container_name: postgresql
    restart: always
    networks:
      - network_odoo
    volumes:
      - '/home/portainer/docker/postgresql/postgresql_data:/bitnami'

  odoo:
    image: 'bitnami/odoo:latest'
    container_name: Odoo
    restart: always
    labels:
      kompose.service.type: nodeport
    networks:
      - network_odoo
    ports:
      - '8069:8069'
      - '8071:8071'
    environment:
      - SMTP_HOST=SSL0.OVH.NET  
      - SMTP_PORT=465
      - SMTP_USER=serveur@nbility.fr  
      - SMTP_PASSWORD=******  
    depends_on:
      - postgresql
    volumes:
      - '/home/portainer/docker/odoo/odoo-persistence:/bitnami'

volumes:
  postgresql_data:
    driver: local
  odoo_data:
    driver: local
`
Thank you all for your help because it's been 2 days that I'm looking for.

Looking forward to reading you

Christophe

**Comment by javsalgar** [comment]
Hi,

Could you enter the container, open the `/opt/bitnami/odoo/conf/odoo-server.conf` file and see if the SMTP configuration is there?

**Comment by rizwan92** [comment]
facing same problem here are my logs
![image](https://user-images.githubusercontent.com/19162978/53545080-486b7300-3b4e-11e9-83b9-0b6069fea0a7.png)

**Comment by rizwan92** [comment]
i solved it by giving env variable   SMTP_PROTOCOL="" \
without it will give an error like above it is not mentioned in instructions 
note delete every time your mount host for every deployment

**Comment by andresbono** [comment]
Hi @rizwan92, thanks for letting us know. We are going to update the README to document the missing option.
