### ISSUE TITLE
The creation of the bitnami_odoo database including demo data is mandatory

### ISSUE THREAD

**Issue by HarlekinSimplex** [bitnami/bitnami-docker-odoo#48]
**Description**
I tried to use the container env variables to define a non default odoo database without demo data.
But it looks like bitnami/bitnami-docker-odoo does only support the initial creation of the default database bitnami_odoo with demo data.

**Steps to reproduce the issue:**
n.a

**Describe the results you received:**
Default database bitnami_odoo with demo data.

**Describe the results you expected:**
The initialization process creates a database "myDatabase" without demo data.

**What you expect to happen**
Its possible to set up docker-compose environment variables to configure the initial database creation process.
- options to configure the database name
- options to configure the database user and password
- options to enable / dissable the demo data

**Comment by tompizmor** [comment]
Hi @HarlekinSimplex,

Yes, it seems at this moment is not possible to deploy Odoo without demo data but in my opinion, it should be possible. I will create a task in our internal system so we can work on fix this for future Odoo releases. 
We will update this issue once we have further information.

**Comment by TheDailySpank** [comment]
As a workaround, you can go to http://[your_server]/web/database/manager > "Create New Database" using the password from the docker-compose.yml file and do not check the "Load demonstration data" option at the bottom. Finally, delete the initial database and load the new one.

**Comment by tompizmor** [comment]
Thanks for providing the workaround! I will increase the priority of the task to check if we can get this done.

**Comment by ruddy32** [comment]
Using **without_demo** flag in odoo configuration file might solve the problem.
 `without_demo=all`

**Comment by carrodher** [comment]
Thanks for your comment, due to other priorities we didn't work on the task created to add this feature, I just added this information to the task and raised the priority. Thanks!

**Comment by ruddy32** [comment]
Is it possible to contribute to update nami configuration files in odoo package ? How ?

**Comment by carrodher** [comment]
I am sorry but Odoo is based on nami logic (NodeJS in the background) and this logic is not public. We're working on migrating our applications from this hide nami logic to public bash logic, for example, see [this note](https://github.com/bitnami/bitnami-docker-prestashop#176-8-debian-10-r1) about PrestaShop.

As there are a lot of applications we are migrating them little by little according to our capabilities taking into account we are a small team. At this moment we already migrated all the infrastructure apps (nginx, apache, databases, metrics, etc) and we are working on web applications (Wordpress, joomla, prestashop, etc) so Odoo is close to being migrated to a public bash logic but at this moment it is not possible.

The above paragraphs are related to the contribution question (thanks for your offer), regarding the initial issue, I raised the priority and it seems we will start working on it during our next sprint.

**Comment by migruiz4** [comment]
Hi,
Latest release of `bitnami-docker-odoo` has `without_demo=all` configured by default. Its value can be modified using the Enviroment variable `WITHOUT_DEMO` which allows the values:
- 'all': Disables demo data for all the modules.
- comma-separated list of modules: Disables demo data for the listed modules.
- '' (empty string): demo data enabled for all the modules.
If you have any further question please let me know
