### ISSUE TITLE
smtp server configuration ist not set up as specified

### ISSUE THREAD

**Issue by HarlekinSimplex** [bitnami/bitnami-docker-odoo#49]
**Description**

Definition of admin user with smtp configuration ist not set up into the demo database.
Just the admin user ist created as specified but not the outbound smtp email server.

**Steps to reproduce the issue:**

1. docker-compose up with following environment:

      - ODOO_EMAIL=admin.dev@your-host.de
      - ODOO_PASSWORD=admin
      - SMTP_HOST=sslou.smtp.provider.eu
      - SMTP_PORT=465
      - SMTP_USER=dev.odoo@your-host.de
      - SMTP_PASSWORD=xxxxxx
      - SMTP_PROTOCOL=ssl

**Describe the results you received:**
The admin user was set up
The smtp server was not set up

**Describe the results you expected:**
The user and the smtp server is set up as specified

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
- Output of `docker version`:
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.8
 Git commit:   9f07f0e-synology
 Built:        Fri May 11 13:41:13 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8
 Git commit:   9f07f0e-synology
 Built:        Fri May 11 13:41:13 2018
 OS/Arch:      linux/amd64
 Experimental: false
```
- Output of `docker info`:
```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.05.0-ce
Storage Driver: btrfs
Logging Driver: db
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: fd189da3e13a3ef3d6d9eb73c5cd4697b4536cdd (expected: 9048e5e50717ea4497b757314bad98ea3763c145)
runc version: a2d6e07aab95ff37fb63cf5dec3c40d29940194f (expected: 9c2d8d184e5da67c95d601382adf14862e4f2228)
init version: 7a83305 (expected: 949e6fa)
Security Options:
 apparmor
Kernel Version: 3.10.105
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.719GiB
Name: MediaStore
ID: GWPW:3RUY:A2WH:CGVU:EC2T:SNWP:W36S:JIEV:LKLS:APNG:5SYW:5LAN
Docker Root Dir: /volume1/@docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

- Output of `docker-compose version` (if applicable):
```
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```
**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Images:
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
bitnami/odoo         latest              ba6f15c4c463        10 hours ago        979MB
bitnami/postgresql   latest              95fc4414df9d        17 hours ago        180MB

**Comment by tompizmor** [comment]
Hi @HarlekinSimplex,

I see that the SMTP settings are configured in the _/opt/bitnami/odoo/odoo-server.conf_ file. 

```
smtp_password = xxxxxxxxx
smtp_port = 587
smtp_server = smtp.gmail.com
smtp_ssl = tls
smtp_user = xxxxxxxxxxx@gmail.com
```

How are you checking if the SMTP is properly configured?

**Comment by HarlekinSimplex** [comment]
Just go to the outgoing email server configuration. You will see that only localhost is configured.
Alternative you may try to create a new user and try to send him the welcome email.
To see the email configuration menu items you need to activate the developer mode in the general settings.

Cheers
Stephan



-----Original Message-----

**Comment by javsalgar** [comment]
Hi,

I saw that now, the SMTP configuration in odoo-server.conf is being ignored. Now it is being stored in the table `ir_mail_server`. I will open a task for updating the container. As it is not a critical issue, we cannot guarantee an ETA. 

Thanks for reporting

**Comment by javsalgar** [comment]
Hi,

We just released a new revision that fixes the SMTP issue. Do not hesitate to reopen the issue in case you find more errors.

**Comment by rizwan92** [comment]
facing same error I have added SMTP details but it is saying enter SMTP host port username etc ...

**Comment by andresbono** [comment]
Hi @rizwan92, please check #46. We updated the README thanks to your feedback 👍
