### ISSUE TITLE
how to integrate ssl in this bitnamee/odoo image 

### ISSUE THREAD

**Issue by rizwan92** [bitnami/bitnami-docker-odoo#55]
there is no documentation or instructions to intgrate ssl in this image for letsencrypt

**Comment by andresbono** [comment]
Hi @rizwan92, did you take a look at our helm charts?

[helm/charts - stable/odoo](https://github.com/helm/charts/tree/master/stable/odoo)

When you want to deploy your application in a production environment where you need SSL enabled we recommend to use Kubernetes to orchestrate the containers. You can make use of the [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) component to expose your service with SSL certificates.

**Comment by rizwan92** [comment]
yeah I looked at it but its  Kubernetes I don't  know  Kubernetes, I am mostly a docker guy, can you please guide how to add extra add-ons volume path and SSL ? its is very urgent for me

**Comment by andresbono** [comment]
@rizwan92, maybe you can use the nginx container as a proxy server. We recommend Kubernetes for production environments, though.

In any case, here you have some steps:

1. Modify the docker-compose.yml file:

See that the odoo container doesn't expose the ports now. Note the volumes of the nginx container:
- A virtual host configuration file for odoo that you will later create.
- The letsencrypt files for your domain.

```diff
       - 'postgresql_data:/bitnami'
   odoo:
     image: 'bitnami/odoo:11'
-    ports:
-      - '80:8069'
-      - '443:8071'
     volumes:
       - 'odoo_data:/bitnami'
     depends_on:
       - postgresql
+  proxy:
+    image: 'bitnami/nginx:latest'
+    ports:
+      - '80:8080'
+      - '443:8443'
+    volumes:
+      - './odoo.conf:/opt/bitnami/nginx/conf/vhosts/odoo.conf'
+      - '/path/to/letsencrypt/certs/live/example.com/fullchain.pem:/opt/letsencrypt-certs/fullchain.pem'
+      - '/path/to/letsencrypt/certs/live/example.com/privkey.pem:/opt/letsencrypt-certs/privkey.pem'
+      - '/path/to/letsencrypt/certs/live/example.com/chain.pem:/opt/letsencrypt-certs/chain.pem'
+
 volumes:
   postgresql_data:
     driver: local
```

2. Add a virtual host configuration file for odoo to nginx (in this example, odoo.conf):

Note that this is an example configuration. Please, modify it to suit your specific needs. For more information, please check https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/.

```
server {
    # Update this line to be your domain
    server_name  example.com;

    ssl_certificate           /opt/letsencrypt-certs/fullchain.pem;
    ssl_certificate_key       /opt/letsencrypt-certs/privkey.pem;
    ssl_trusted_certificate   /opt/letsencrypt-certs/chain.pem;

    listen [::]:8443 default_server ipv6only=off ssl;
    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;

    proxy_buffering off;

    location / {
        proxy_pass http://odoo:8069;
        proxy_set_header Host $host;
        proxy_redirect http:// https://;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

3. Restart your containers

```
docker-compose down && docker-compose up
```

**Comment by rizwan92** [comment]
thank you @andresbono  for guiding me how to add nginx proxy in this image it helped me a lot, to undestrand this image. but i was asking for extra addons volume path in bitnami/odoo image. 

when you want to integrate extra  packages or theme in odoo , odoo provides extra path volumes for extra-addons but. in bitnami there is no documentation for extra-addons path

**Comment by andresbono** [comment]
Oh ok @rizwan92! Is `/opt/bitnami/odoo/addons` the directory that you are looking for?

**Comment by rizwan92** [comment]
thank you @andresbono is bitnami only provide odoo 11 image, there is new release of odoo 12. how can migrate to that ?

**Comment by andresbono** [comment]
@rizwan92, we don't have the container for Odoo 12 yet

**Comment by andresbono** [comment]
Hi @rizwan92, we started the work to support the Odoo 12 image. Once we release it, we will let you know!

**Comment by rizwan92** [comment]
thank you @andresbono  looking forward to try odoo 12 images, bitnami always helps me to try different images in very easy way, 

> Hail bitnami

.

**Comment by carrodher** [comment]
Hi, we just released Odoo 12, you can find it in this folder: https://github.com/bitnami/bitnami-docker-odoo/tree/master/12/debian-9

**Comment by TheDailySpank** [comment]
@rizwan92 After trying a lot of different things, I found https://github.com/SteveLTN/https-portal.

Add it into your docker-compose.yml file like it says in the quick start, and change the line

```
DOMAINS: 'wordpress.example.com -> http://wordpress:80'
```
to

```
DOMAINS: '[your_domain_name] -> http://odoo:8069'
```
and start it up again.

You might also want to add/edit ```CLIENT_MAX_BODY_SIZE: '100M'``` to the https-portal > environment section if you want to be able to upload backups. The default is 1M.

**Comment by rizwan92** [comment]
I think this image solves my lots of problems. Hail Bitnami! and thank you @TheDailySpank

**Comment by andresbono** [comment]
Nice @TheDailySpank, thanks for the tip!

@rizwan92, I'm closing this issue. Feel free to open a new one if you need further help!

**Comment by rizwan92** [comment]
hey @andresbono I have a question for the bitnami organization , like if there is any image which is very popular millions of pulls there and bitnami don't support that image for now. if I want to suggest them there are more images to explore and have millions of pull in it how can I give this kind of suggestion to bitnami

**Comment by andresbono** [comment]
Hi @rizwan92, you can send your suggestions to support@bitnami.com. It will be greatly appreciated!

**Comment by isaac1304** [comment]
Hi @andresbono! Nice to meet you. I am trying to mount Odoo image over a Kubernetes, seem like all is working fine, but I am unable to get access using nginx ingress controller... Still I need an nginx container to work as proxy in this case? I am not sure if Odoo image has an web server inside to take those request, I am getting and 502 error.
<img width="970" alt="image" src="https://user-images.githubusercontent.com/7354207/86431569-5dac6080-bcb2-11ea-83b5-73357965adc1.png">
 
--The nginx ingress is taking the request, but is unable to communicate with odoo:
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/7354207/86431600-7a489880-bcb2-11ea-8efc-87dfff5d2024.png">


--Logs of Odoo container:
<img width="883" alt="image" src="https://user-images.githubusercontent.com/7354207/86431357-d8c14700-bcb1-11ea-85f3-a444d394affd.png">

--Ingress configuration:
`apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: odoo-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: odoo.granados.cr
    http:
      paths:
      - path: /
        backend:
          serviceName: odoo-service
          servicePort: 80`

--Ingress deployed:
<img width="589" alt="image" src="https://user-images.githubusercontent.com/7354207/86431464-17570180-bcb2-11ea-9d6b-b746dc268399.png">

Thank you in advance for your help or advices!

**Comment by isaac1304** [comment]
Hello @andresbono! I am trying to install Odoo using docker images, into a Kubernetes cluster... Seems like all is working fine but I am getting this error when try to install the Odoo:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/7354207/86436336-4de74900-bcbf-11ea-91d9-3f979ba8cc2d.png">
 Any idea about how to avoid this problem? I tried the installation with helm, but it is less configurable.

**Comment by andresbono** [comment]
@isaac1304, it looks like a different issue, we opened #89.
