### ISSUE TITLE
Postgres install - DETAIL: Permissions should be u=rwx (0700)

### ISSUE THREAD

**Issue by gridworkz** [bitnami/bitnami-docker-odoo#60]
Hi Guys:

I get this error on one of our clusters when installing the latest Odoo Helm chart: 0.7.0. It happens when it's installing the Postgresql portion. For some reason it thinks the /opt/bitnami/postgresql directory is world readable even though I can clearly see the init-chmod commands setting the directory permissions correctly.

....
DETAIL: Permissions should be u=rwx (0700) 
....

This is a clean install with no stale PVs / PVCs hanging around or anything.

A little more info:

INFO ==> ** PostgreSQL setup finished! **
INFO ==> ** Starting PostgreSQL **
2019-05-09 20:25:51.466 GMT [1] LOG: skipping missing configuration file "/bitnami/postgresql/postgresql.auto.conf"
2019-05-09 20:25:51.466 GMT [1] FATAL: data directory "/bitnami/postgresql" has group or world access
2019-05-09 20:25:51.466 GMT [1] DETAIL: Permissions should be u=rwx (0700).

It's like there's a PV there already causing it to fail - but I can't seem to identify which one it is.

Cheers,
Dave

**Comment by juan131** [comment]
Hi @gridworkz 

Thanks for reporting it.

This issue is being discussed on the PostgreSQL repo. Please let's continue the discussion there to avoid multiple threads about the same topic:

https://github.com/bitnami/bitnami-docker-postgresql/issues/134
