### ISSUE TITLE
Some Good News!

### ISSUE THREAD

**Issue by gridworkz** [bitnami/bitnami-docker-odoo#61]
Hi Guys:

I have some good news for a change! I installed the latest Odoo Helm chart 8.0 (postgresql working fine now btw). I have pgbouncer and a Patroni cluster running on my K8 cluster. I pointed the Odoo instance to pgbouncer and viola - Odoo connects just fine. It's a bit of a hack of odoo-server.conf but it serves its' purpose for us now.

Thanks for all your help. 
Dave-o

**Comment by juan131** [comment]
That's great @gridworkz !!! I'm very glad you were able to configure Odoo to use your Patroni cluster using **pgbouncer**

Once we add support to external databases on this image as you requested in #59, you should be able to easily configure Odoo to use an external cluster as database too.

**Comment by smirnov-mi** [comment]
Hi guys, 
does bitnami/odoo image supports the external PG (Patroni cluster in my case as well) now? I'm trying to make it work but failing with following, after a minute or two of configuring itself:

```
psycopg2.OperationalError: could not create SSL context: library has no ciphers
FATAL:  pg_hba.conf rejects connection for host "10.1.1.1", user "bn_odoo", database "postgres", SSL off

```

i'm on k8s 1.16.2, helm3, chart patroni-0.15.0 (PG 11.5), odoo12 image 12.0.20191215-debian-9-r11 .    And pretty new to all these things.

**Comment by smirnov-mi** [comment]
Looks like it works after all. I had to open nossl  connections in the pg.conf
