### ISSUE TITLE
Odoo chart deployment in rancher 2 issue

### ISSUE THREAD

**Issue by tamtamaouy** [bitnami/bitnami-docker-odoo#65]
Hi,
I try to deploy odoo in rancher 2 but I have this error 
```
Liveness probe failed: Get http://10.42.2.49:80/: dial tcp 10.42.2.49:80: connect: connection refused
```
I tried to increase the value to 1H and also the readiness but I have the same error

and in the log doesn't show any error, only (if I remember correctly) nami initializing odoo

If someone can help me it will very appreciable, I spent 1 week to trie understand whats the cause but I was not able.

thanks in advance.

**Comment by carrodher** [comment]
Hi, are you using the default _values.yaml_ using `helm install` or you implemented some changes in the file or used some flags in the install command?
What is the result of executing `kubectl logs XXXXX`? Where _XXXX_ is the pod name obtained by running `kubectl get pods`
