### ISSUE TITLE
Odoo helm chart with external database going through pgbouncer

### ISSUE THREAD

**Issue by gridworkz** [bitnami/bitnami-docker-odoo#66]
Hi Guys:

First off thanks for adding external database access to the Odoo Helm chart! A real time saver. It works perfectly if I attach directly to my K8 Postgres db cluster (Crunchy). 

However, my client requires pgbouncer for Odoo.  When I use pgbouncer endpoint as my external database I get an auth failed when trying to start Odoo. I think I can guess what's happening - You try to create a bn_odoo user in Postgres to create the bitnami_odoo database.  bn_odoo user does not exist in the userlist.txt file for pgbouncer so it won't let bn_odoo through. So I add a bn_odoo user to userlist.txt but what password do I use? Because one is randomly generated by Bitnami, sort of a chicken/egg situation. Anyway, here's the error that I get if I add a bn_odoo user to pgbouncer with password "odoo" then try to install Odoo:

Welcome to the Bitnami odoo container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-odoo
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-odoo/issues
nami INFO Initializing odoo
odoo INFO Configuring Odoo database...
postgre INFO Trying to connect to PostgreSQL server
postgre INFO Found PostgreSQL server listening at pgbouncer-fslibre.default.svc.cluster.local:5432
postgre INFO PostgreSQL server listening and working at pgbouncer-fslibre.default.svc.cluster.local:5432
odoo INFO Preparing Odoo environment...
odoo INFO Starting Odoo...
Error executing 'postInstallation': Unable to start com.bitnami.odoo: Traceback (most recent call last):
File "odoo-server", line 9, in <module>
odoo.cli.main()
File "/opt/bitnami/odoo/odoo/cli/command.py", line 60, in main
o.run(args)
File "/opt/bitnami/odoo/odoo/cli/server.py", line 176, in run
main(args)
File "/opt/bitnami/odoo/odoo/cli/server.py", line 140, in main
odoo.service.db._create_empty_database(db_name)
File "/opt/bitnami/odoo/odoo/service/db.py", line 95, in _create_empty_database
with closing(db.cursor()) as cr:
File "/opt/bitnami/odoo/odoo/sql_db.py", line 657, in cursor
return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
File "/opt/bitnami/odoo/odoo/sql_db.py", line 171, in __init__
self._cnx = pool.borrow(dsn)
File "/opt/bitnami/odoo/odoo/sql_db.py", line 540, in _locked
return fun(self, *args, **kwargs)
File "/opt/bitnami/odoo/odoo/sql_db.py", line 608, in borrow
**connection_info)
File "/opt/bitnami/odoo/venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: ERROR: Auth failed
: Traceback (most recent call last):
File "odoo-server", line 9, in <module>
odoo.cli.main()
File "/opt/bitnami/odoo/odoo/cli/command.py", line 60, in main
o.run(args)
File "/opt/bitnami/odoo/odoo/cli/server.py", line 176, in run
main(args)
File "/opt/bitnami/odoo/odoo/cli/server.py", line 140, in main
odoo.service.db._create_empty_database(db_name)
File "/opt/bitnami/odoo/odoo/service/db.py", line 95, in _create_empty_database
with closing(db.cursor()) as cr:
File "/opt/bitnami/odoo/odoo/sql_db.py", line 657, in cursor
return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
File "/opt/bitnami/odoo/odoo/sql_db.py", line 171, in __init__
self._cnx = pool.borrow(dsn)
File "/opt/bitnami/odoo/odoo/sql_db.py", line 540, in _locked
return fun(self, *args, **kwargs)
File "/opt/bitnami/odoo/odoo/sql_db.py", line 608, in borrow
**connection_info)
File "/opt/bitnami/odoo/venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: ERROR: Auth failed

I assume this is bn_odoo trying to get through pgbouncer. Any pointers greatly appreciated.

btw: Here's the parms I'm sending down to Helm chart (basically your image with some extra python libs I use - it's based on your latest image):

image.repository=griderp/bn-addons
image.tag=latest
odooUsername=admin
odooPassword=AnewSecurePazz256
ingress.hosts[0].name=contastico.com
ingress.hosts[0].tls=true
ingress.hosts[0].certManager=true
ingress.hosts[0].tlsSecret=contastico-com-tls-prod
persistence.storageClass=fslibre-nfs-sc1
persistence.accessMode=ReadWriteMany
postgresql.enabled=false
externalDatabase.host=pgbouncer-fslibre.default.svc.cluster.local
externalDatabase.user=postgres
externalDatabase.password=odoo

Cheers,
Dave

**Comment by rafariossaa** [comment]
Hi @gridworkz ,
  Thanks for you kind words.

  If you set an external database, the user and password used to connect are externalDatabase.user and externalDatabase.password, the database name is bitnami_oddo. So, before hand you have to create and gave proper permissions to the user to that database.

**Comment by gridworkz** [comment]
Got a little further by modifying pgbouncer with a more advanced auth mechanism from here: https://www.cybertec-postgresql.com/en/pgbouncer-authentication-made-easy/#

Now, I don't get the above error but now it just sits there looking for modules in the list for 180s and times out. I'm going to find a better way to do connection pooling with Crunchy...

**Comment by gridworkz** [comment]
Thanks, I'll give that a try...
Cheers,
Dave

**Comment by gridworkz** [comment]
It's the wackiest thing - I attach directly to my Postgres cluster:
(external db host - pgset-0.pgset.default.svc.cluster.local) Odoo installs
perfectly.

When I try to install Odoo using pgbouncer as the external db (host -
pgbouncer-fslibre.default.svc.cluster.local) I watch the Odoo log and it
gets to '....searching for modules from ../logs/odoo-server.log' and waits
180s and times out. There's nothing much appearing in the pgbouncer logs -
it just says it receives bad info from the Odoo login query - very vague.

I can connect to the database cluster via psql from my local machine no
problem through pgbouncer so I know that pgbouncer is working ok. I have
the query_timeout set to 0 in pgbouncer which basically says wait
indefinitely for a query to finish so I don't think it's a timing issue.
There's just something K8 Bitnami Odoo doesn't like about pgbouncer.

It's not a deal breaker so we can keep going. My main concern is when we
ramp up the volume of connections in our Odoo cluster. Maybe K8 will handle
it ok. I just thought I would bring the issue to your attention. I'm around
to test if you want to chase this further.

Cheers,
Dave

**Comment by gridworkz** [comment]
Actually, I think it's a pgbouncer / auth_user issue.
https://github.com/pgbouncer/pgbouncer/issues/149 They're getting the same
message I get.   psql: ERROR: unexpected response from login query

Not a Bitnami Odoo issue...

**Comment by gridworkz** [comment]
ok fixed - the pgbouncer user lookup function needs to be created in
template1 so it's available to all database that are created. Sort of
available globally....the function was originally only created in the
postgres db therefore it didn't give the pgbouncer user any access to other
databases. Happy happy now....
Cheers,
Dave

**Comment by andresbono** [comment]
Great to hear @gridworkz! :tada:
