### ISSUE TITLE
How to add custom addons folder in container

### ISSUE THREAD

**Issue by lex4vn** [bitnami/bitnami-docker-odoo#68]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
Hi @lex4vn 

Could you please provide more information about what you are trying to achieve? 
What did you try so far? How could I reproduce your issue locally?
What version of the Odoo docker image are you using? Are you using docker-compose to deploy the containers (if so provide which **docker-compose.yaml** you used)? 
Thanks in advance

**Comment by gridworkz** [comment]
I think a lot of us are trying to get custom addons into the Bitnami Odoo image via the Dockerfile possibly using the COPY command. Personally, I'm trying to get some custom addons copied to /opt/bitnami/odoo/data/addons/12.0 directory during the build. I always have to manually copy my addons to this directory once the pod is created.

**Comment by juan131** [comment]
Hi @gridworkz 

As you can check, both the **/addons** and **/data/addons** directories are persisted on this Docker image (available under the persisted directory **/bitnami/odoo**):

```
# tree /bitnami/odoo/
/bitnami/odoo/
|-- addons
|-- data
|   |-- addons
|   |   `-- 12.0
|   `-- filestore
...
```

Therefore, you should copy them to those directories.

Regarding how to automate this process so the add-ons are available every time you create a new pod, you could try to modify [this script](https://github.com/bitnami/bitnami-docker-odoo/blob/master/12/debian-9/rootfs/app-entrypoint.sh#L10) so you add your logic to add your add-ons (e.g. downloading the add-ons during the initialization):

```diff
  nami_initialize odoo
+ ## Put your logic here
  info "Starting odoo... "
```

**Comment by gridworkz** [comment]
Hi Juan:

Nice, exactly what I was looking for.

Cheers,
Dave

**Comment by gridworkz** [comment]
Hi Juan:

The addons stuff worked perfectly.

I have one last question and I think that should be it.

Is it possible to setup a new customer by just using your Helm chart?
Adding the ingress and cert and everything?

Here's what I run now when a new customer signs up:

1) Create/Run this yaml command to issue a Letsencrypt client cert into the
cluster (*<company-name>*-*<tld>*-prod-http01.yaml):
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: *<company-name>*-prod
spec:
  acme:
    email: dave@gridworkz.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: *<company-name>*-*<tld>*-account-key
    http01: {}

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: *<company-name>*-*<tld>*-prod
spec:
  secretName: *<company-name>*-*<tld>*-tls-prod
  issuerRef:
    name: *<company-name>*-prod
  commonName: www.*<company-name>*.*<tld>*
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - www.*<company-name>*.*<tld>*
      - *<company-name>*.*<tld>*

2) Run your Helm chart to create Odoo instance on the cluster:

pwgen 10 1 (generate a password)
helm install --name *<company-name>*-odoo \
  --set
image.repository=griderp/bn-addons,image.tag=latest,odooUsername=admin,odooPassword=
*<password>*,persistence.storageClass=gridworkz-nfs-sc1,persistence.accessMode=ReadWriteMany,postgresql.enabled=true,postgresql.postgresqlPassword=odoo,postgresql.persistence.storageClass=openebs-cstor-sparse
\
    stable/odoo

3) Run this command to create an Ingress for the new Odoo instance:
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: *<company-name>*-ingress
  namespace: default
  annotations:
    certmanager.k8s.io/issuer: *<company-name>*-prod
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/acme-dns01-provider: acme-dns
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - www.*<company-name>*.*<tld>*
    - *<company-name>*.*<tld>*
    secretName: *<company-name>*-*<tld>*-tls-prod
  rules:
  - host: www.*<company-name>*.*<tld>*
    http:
      paths:
      - path: /
        backend:
          serviceName: *<company-name>*-odoo
          servicePort: http

I was looking through the latest Odoo Helm chart and I noticed that I could
possibly consolidate a lot of this stuff into the helm chart parameters. Do
you have an example of a full blown helm chart filled with sample
parameters? For example, I have a number of annotations in my ingress.yaml
above and it looks as though these could be incorporated into the helm
chart parameter (ingress.hosts[0].annotations). I'm just not sure of the
syntax, hence the example request.

I'm just wondering if I could create a new client Odoo instance in one shot
as opposed to doing the extra steps above.

BTW: I run everything for my Odoo subscription service at GKE.

Cheers,
Dave

**Comment by andresbono** [comment]
Hi @gridworkz, it seems you are creating 3 objects apart from executing the helm chart install command.

At least, the ingress object, can be created with the helm chart itself. In order to get a similar configuration to the one you shared with us, you can try the `helm template` command, it is really useful in these situations. You can do the following:

```
helm template stable/odoo -x templates/ingress.yaml \
    --set ingress.enabled=true
    --set ingress.hosts[0].name=www.company-name.tld
```

And it will show the ingress object that the chart will create for you. That way, you can quickly try the different parameters specified in the [README.md](https://github.com/helm/charts/tree/master/stable/odoo#configuration) that you will need to set up.

About the certificates, you should be able to add some annotations (see [`ingress.hosts[0].certManager`](https://github.com/helm/charts/tree/master/stable/odoo#configuration)) that will make that the certificate-manager service installed in your cluster issues a certificate for Odoo. See https://docs.cert-manager.io/en/latest/tasks/issuing-certificates/ingress-shim.html for more information.

**Comment by gridworkz** [comment]
Hi Andres:

Ah, good to know about the templates. I'll check that out. Regarding the
certs - GKE requires a cert issuer or clusterIssuer to exist prior to
running my Odoo Helm chart. So the annotations in my values.yaml file need
to look like this:

....
    annotations:
      certmanager.k8s.io/issuer: *shb-prod*
      certmanager.k8s.io/acme-challenge-type: http01
      certmanager.k8s.io/acme-dns01-provider: acme-dns
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
      nginx.ingress.kubernetes.io/send-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-body-size: 500m
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: true
....

This Issuer name needs to exist on the cluster prior to running my Odoo
Helm chart. So I run this prior to running my Helm chart:

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: *shb-prod*
spec:
  acme:
    email: dave@gridworkz.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: shb-com-account-key
    http01: {}

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: shb-com-prod
spec:
  secretName: shb-com-tls-prod
  issuerRef:
    name: *shb-prod*
  commonName: www.skunkhollowbud.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - www.skunkhollowbud.com
      - skunkhollowbud.com

I haven't been able to include this initial (Issuer/Certificate) step with
just Helm chart parameters alone.

Cheers,
Dave

**Comment by gridworkz** [comment]
Hi Andres:

fyi:
I tried to set this: --set ingress.hosts[0].annotations= and it gives me an
iteration error but if I use this: --set ingress.hosts[0].annotation= (no
"s") it works but doesn't insert any annotations in the template output.

Cheers,
Dave

**Comment by juan131** [comment]
Hi @gridworkz 

I recommend you to edit the **values.yaml** to add the annotations. It's a nightmare to do it through the command line. Once you have your own **values.yaml**, you can install Odoo running:

```console
$ helm install stable/odoo -f my-custom-values.yaml
```

By the way, we have a guide that explains the process to use **cert-manager** to provide TLS certificates automatically on your cluster to your applications. This guide uses **Joomla!** as the example application to install but the steps to do the same with Odoo are identical.

https://docs.bitnami.com/kubernetes/how-to/secure-kubernetes-services-with-ingress-tls-letsencrypt/

**Comment by gridworkz** [comment]
Hi Juan:

Awesome thanks...

Cheers,Dave

**Comment by juan131** [comment]
You're welcome @gridworkz ! I also recommend you to take a look to our engineering blog where you can find great articles about K8s and other cloud technologies:

https://engineering.bitnami.com/

**Comment by M-Adeel-Danish** [comment]
Hi bitnami team,
Thank you guys for your great work.

I am having the same issue with docker image, external addons are not appearing in apps. I have followed all instructions in this thread, double-checked everything. Addons are where they supposed to be.

`root@2e10c91e7693:/bitnami/odoo/addons# ls
muk_autovacuum  muk_utils  muk_web_theme  muk_web_utils`

Updated apps list without results. 

`Kernel Version: 5.8.6-1-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 Debug Mode: false`

Kindly suggest what could go wrong.

**Comment by juan131** [comment]
Hi @M-Adeel-Danish 

Could you tr `addons_path = /opt/bitnami/odoo/odoo/addons

**Comment by M-Adeel-Danish** [comment]
Thank you @juan131 it worked. I thought the directory was connected via symlink apparently it was not.

**Comment by juan131** [comment]
Hi @M-Adeel-Danish 

Thanks for confirming it!!

I will include a patch in next versions so it include that path by default in the `addons_path` property.
