### ISSUE TITLE
Workers

### ISSUE THREAD

**Issue by gridworkz** [bitnami/bitnami-docker-odoo#69]
I notice I can't add workers to my odoo-server.conf file. It's not an issue for me I was just curious why we can't use them. Is it a Kubernetes / Pod thing?

**Comment by javsalgar** [comment]
Hi,

It's true that multi-processing, even though it may depend on the hardware specs of the target system, could be an interesting parameter to configure via environment vars. Thanks for the feedback, we will evaluate it for future releases.

**Comment by marcosbc** [comment]
Hi @gridworkz, we just released `12.0.20210615-debian-10-r20`/`13.0.20210610-debian-10-r24`/`14.0.20210610-debian-10-r22` versions of this container which includes a major refactor of the existing logic. Refer to the [Notable Changes section in the README](https://github.com/bitnami/bitnami-docker-odoo#notable-changes) for more info.

In addition, now an [`odoo.conf.tpl` template](https://github.com/bitnami/bitnami-docker-odoo/blob/master/14/debian-10/rootfs/opt/bitnami/scripts/odoo/bitnami-templates/odoo.conf.tpl) is present in this repo, which you can use to build a custom container image with a custom value for `workers`. Alternatively, you could mount the file at runtime in `/opt/bitnami/scripts/odoo/bitnami-templates/odoo.conf.tpl` and the custom configuration would be applied.

That should allow you to apply advanced configurations for this image.

**Comment by gridworkz** [comment]
Sweet! We'll check it out.
Dave
