### ISSUE TITLE
issue about network

### ISSUE THREAD

**Issue by xiao1201** [bitnami/bitnami-docker-odoo#71]
Hi I'm pretty new to Git and Docker so I'm sorry if what i ask is inappropriate.
My question is: can I use my own internal network, say, name "bridge", ip 172.17.0.x, instead of "odoo-tier", ip 172.27.0.x? Your docker run command of creating the odoo and database containers are fine, i have no problem of running them. But when I change the parameter "--net odoo-tier" to "bridge", then I found odoo couldn't connect to the database. So network "odoo-tier" is mandatory? Can I change it? Thank you.

**Comment by marcosbc** [comment]
Hi @xiao1201, you can use any existing Docker network, but the database must be in the same network as the Odoo container or else it won't work.

You could also run your database in a public service such as RDS to workaround, but this probably doesn't make much sense for you right now. The easiest approach is placing both containers in the same network.

**Comment by xiao1201** [comment]
Hi @marcosbc, thanks for the reply. I tried again, but the problem is still that the odoo couldn't connect to PostgreSQL. They're in the same network one with ip 172.17.0.9 and another 172.17.0.10.

PostgreSQL has the following log:

INFO  ==> ** Starting PostgreSQL setup **


INFO  ==> Validating settings in POSTGRESQL_* env vars..


WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.


INFO  ==> Initializing PostgreSQL database...


INFO  ==> postgresql.conf file not detected. Generating it...


INFO  ==> pg_hba.conf file not detected. Generating it...


INFO  ==> Deploying PostgreSQL with persisted data...


INFO  ==> Configuring replication parameters


INFO  ==> Configuring fsync


INFO  ==> Loading custom scripts...


INFO  ==> Enabling remote connections


INFO  ==> Stopping PostgreSQL...


INFO  ==> ** PostgreSQL setup finished! **


INFO  ==> ** Starting PostgreSQL **


2019-08-20 06:23:11.786 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432


2019-08-20 06:23:11.786 GMT [1] LOG:  listening on IPv6 address "::", port 5432


2019-08-20 06:23:11.791 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"


2019-08-20 06:23:11.849 GMT [112] LOG:  database system was shut down at 2019-08-18 05:57:20 GMT


2019-08-20 06:23:11.879 GMT [1] LOG:  database system is ready to accept connections

and the odoo logs:

nami    INFO  Initializing odoo


odoo    INFO  Configuring Odoo database...


postgre INFO  Trying to connect to PostgreSQL server


Error executing 'postInstallation': Failed to connect to postgresql:5432 after 36 tries

somehow the odoo fails to connect to the database, and after 36 tries the odoo container stopped running.

**Comment by marcosbc** [comment]
Hi @xiao1201, could you share your docker-compose file so we can try to reproduce the issue on our side?

Also, please share the result of running this command inside the container, note that you should see the same output (it shouldn't timeout):

```
$ curl http://postgresql:5432
curl: (52) Empty reply from server
```

**Comment by xiao1201** [comment]
Hi @marcosbc , I didnt use docker-compose, I used docker run commands to creates the containers:
1. Postgresql creation:
'''sh
docker run -d --name postgresql --net bridge -e ALLOW_EMPTY_PASSWORD=yes bitnami/postgresql:latest
'''
2. Odoo creation:
'''sh
docker run -d -e VIRTUAL_HOST=erp.xxx.xx -p 8082:8069 -p 443:8071 --name odoo --net bridge bitnami/odoo:latest
'''

running 'curl http://postgresql:5432' from odoo container:
curl: (6) Could not resolve host: postgresql

**Comment by marcosbc** [comment]
Hi @xiao1201, that is because you haven't configured any network alias for the PostgreSQL container.

Unfortunately that requires you to use a user-defined network or you will get this error:

```
docker: Error response from daemon: network-scoped alias is supported only for containers in user defined networks.
ERRO[0000] error waiting for container: context canceled
```

Therefore, create the network:
```
docker network create mynetwork
```

Then run the containers

- PostgreSQL (using the `--net-alias` parameter for the database which you want to access in the other container):

      docker run -d --name postgresql --net mynetwork --net-alias postgresql -e ALLOW_EMPTY_PASSWORD=yes bitnami/postgresql:latest

- Odoo:

      docker run -d -e VIRTUAL_HOST=erp.mydomain.com -p 8082:8069 -p 443:8071 --name odoo --net mynetwork bitnami/odoo:latest

Then it should work for you.

**Comment by xiao1201** [comment]
hi @marcosbc , thank you very much for the reply. My case is that I use nginx-proxy docker to direct different subdomains to my different docker based services with same ip but different ports, e.g., erp.mydomain.com -> ip:8883; mail.mydomain.com -> ip:8882, etc. These services, like mail, odoo, www, along with nginx-proxy are all in the same default network, "bridge". And as nginx-proxy does not support different subnet forwarding, I cannot let odoo use another different subnet. So, in my case, there's no way to solve the issue? Wish I explained clearly.

**Comment by marcosbc** [comment]
Hi @xiao1201, there are people discussing your use case in Docker's official repository (https://github.com/docker/compose/issues/3012 and https://github.com/docker/compose/issues/3476) but unfortunately it doesn't seem like anyone's tracking it.

Since you are forced to use the `bridge` network, then the only things that occurs to me is for you to use the `--link` option for Docker despite it being [deprecated](https://docs.docker.com/network/links/):

- PostgreSQL:

      docker run --name postgresql --net bridge -e ALLOW_EMPTY_PASSWORD=yes bitnami/postgresql:latest

- Odoo (with `--link`):

      docker run -e VIRTUAL_HOST=erp.mydomain.com -p 8082:8069 -p 443:8071 --name odoo --net bridge --link postgresql:postgresql bitnami/odoo:latest

**Comment by xiao1201** [comment]
hi @marcosbc thank you very much for the help! I'll check it out.
