### ISSUE TITLE
Odoo instance creation automation

### ISSUE THREAD

**Issue by gridworkz** [bitnami/bitnami-docker-odoo#72]
Hi Guys:

Just a shot in the dark here but maybe you can help or have some suggestions.

I'm looking to streamline the process of creating a new Odoo instance for each new customer that signs up for a subscription at www.gridworkz.com.

Currently there's a few manual steps I use to create a new Odoo instance.

When a new customer signs up I need to execute one helm command to create the Odoo instance (Your awesome Bitnami Odoo Helm chart). I also offer cert management for the customer which requires me to execute 2 .yaml files 

1) one to issue the new cert from Letsencrypt 
2) create a service and Ingress for them. 

So the workflow goes like this:

1) New customer signs up (post-subscription purchase message indicates to give us 30-60 min to setup instance)
2) engineer runs:
 - cert creation yaml
 - Bitnami Odoo helm chart command to create instance
 - service / ingress creation .yaml
3) secure email sent to client with login credentials to new instance (manual)

I was wondering if there are some ways to maybe distill this down a bit via Helm or somehow automate the .yaml file execution process. It's a small but important manual step that needs to be performed over and over and it might be ripe for automation.

btw: This is the helm command I run:

helm install --name (company-name)-odoo \
  --set image.repository=griderp/bn-addons,image.tag=latest,odooUsername=admin,odooPassword=(password),persistence.storageClass=gridworkz-nfs-sc2,persistence.accessMode=ReadWriteMany,postgresql.enabled=true,postgresql.postgresqlPassword=odoo,postgresql.persistence.storageClass=openebs-cstor-sparse \
    stable/odoo

Also, one other quick question. I created my own image (based on yours) that I use. Works great. I need to add addons to my base image and I was wondering if I can do that using your Dockerfile. (or do I need to dig into the guts of the Debian minideb-extras:stretch-* for that.)

My image is here: https://hub.docker.com/u/griderp/

Cheers,
Dave

**Comment by miguelaeh** [comment]
Hi @gridworkz ,
Related to the automation process to execute the `.yaml` files maybe you can take a look to the [helm hooks](https://github.com/helm/helm/blob/master/docs/charts_hooks.md). You can try to use for example the post-install hook for the service and ingress creation, but have in mind that the resources created by the hook will not be managed as part of the release.

Related to install addons, the bitnami image uses a javascript logic to configure odoo that you can see inside the container at `~/.nami/components/com.bitnami.odoo/`. That logic is called at the `app-entrypoint.sh` with `nami_initialize`.  I think it could be difficult for you to modify but, you can try to insert your own script after that or even modify that script after the `nami_initialize` call.

**Comment by gridworkz** [comment]
Thanks for the tips - I'll try them out.
Cheers,
Dave

**Comment by miguelaeh** [comment]
You're welcome, I hope it will be useful.

**Comment by miguelaeh** [comment]
Hi @gridworkz ,
The command should be executed at this point, for example:
I added this:
```
    10   info "Starting odoo... "
+  11   info "THIS IS MY CODE"
    12 fi
```

And the output shows it:
```
odoo_1        | odoo    INFO
odoo_1        | nami    INFO  odoo successfully initialized
odoo_1        | INFO  ==> Starting odoo...
odoo_1        | INFO  ==> THIS IS MY CODE
odoo_1        | 2019-08-28 08:13:02,596 51 INFO bitnami_odoo odoo.modules.loading: Module web_tour: loading demo
odoo_1        | 2019-08-28 08:13:02,596 51 INFO bitnami_odoo odoo.modules.loading: loading web_tour/data/web_tour_demo.xml
```

So, I would check if that directory exists before you run that command

**Comment by gridworkz** [comment]
Hi Miguel:

Ah OK, thanks I'll do that.

Cheers,
Dave

**Comment by miguelaeh** [comment]
Hi @gridworkz .
Let us know if it worked.
Thanks!

**Comment by gridworkz** [comment]
Still no luck. I'm going to drop everything into a bash script and wait until the pod becomes available then copy everything over.

**Comment by miguelaeh** [comment]
You can also try with an init container mounting the same volume as in the principal container.

**Comment by gridworkz** [comment]
I never thought of that - cool. I'll check it out.
Cheers,
Dave

**Comment by miguelaeh** [comment]
Hi @gridworkz ,
You can modify the templates locally and deploy using `.` instead of `stable/odoo` from the source directory. Just add the init container to every pod you need.

**Comment by gridworkz** [comment]
Hi Miguel:

Thanks, will do.

Cheers,
Dave

**Comment by gridworkz** [comment]
Hi Miguel:

Sorry I forgot to ask. Just to confirm - which template should I alter with
init containers? I assume it's the deployment template.

Cheers,
Dave

**Comment by miguelaeh** [comment]
Right, the deployment template
