### ISSUE TITLE
How to add custom addons in container

### ISSUE THREAD

**Issue by gridworkz** [bitnami/bitnami-docker-odoo#73]
I think a lot of us are trying to copy custom addons into the Bitnami Odoo image via the Dockerfile possibly using the COPY command. Personally, I'm trying to get some custom addons copied to /opt/bitnami/odoo/data/addons/12.0 directory somewhere during the build. I always have to manually copy my addons to this directory *after* the pod is created.

I know you guys mentioned the helm hooks and the javascript logic embedded in the Bitnami system itself but I couldn't come up with anything I could understand to make this work. Helm doesn't really like you adding external files to its' process for security reasons. (However, it can be done I just couldn't figure out how to do it in our context.) We'll need more specific details on the exact spot to inject custom addons into the Bitnami build process.

_Originally posted by @gridworkz in https://github.com/bitnami/bitnami-docker-odoo/issues/68#issuecomment-524140135_

**Comment by juan131** [comment]
Hi @gridworkz 

I noticed you also commented on this [other issue](https://github.com/bitnami/bitnami-docker-odoo/issues/68). I'll continue the discussion there.
