### ISSUE TITLE
Start odoo with --database and --update parameters

### ISSUE THREAD

**Issue by martinkubrak** [bitnami/bitnami-docker-odoo#75]
Hi,

Is it possible to start odoo with --database and --update parameters to update modules before starting the server?

Thanks,
Martin

**Comment by rafariossaa** [comment]
Hi @martinkubrak,
  You can use other database using the `POSTGRESQL_*` parameters.

  Do you  mean to update all the modules or a list of them ?

**Comment by martinkubrak** [comment]
Hi @rafariossaa,

I mean to update list of specific modules. 

I'm trying to hack Bitnami Odoo image to make it work for our scenario. One of the requirements is to have several Odoo deployments each with it's own database but all running on the same database host.

**Comment by rafariossaa** [comment]
Sorry for the delay, I forgot to mention that I have created an internal task to add this feature.

We will come back to you as soon we have news.

**Comment by martinkubrak** [comment]
@rafariossaa thanks!
