### ISSUE TITLE
Odoo not communicate with customized postgres port

### ISSUE THREAD

**Issue by kathpalrk** [bitnami/bitnami-docker-odoo#77]
Hi,

Odoo is not being communicate with different postgres port. But it's working if I am trying to connect from psql cli.

I conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"? - - -
^C2019-11-08 05:47:49,305 439 INFO ? odoo.service.server: Initi

I am using the diff postgresql port which I've already definded under odoo.conf file, but its still not able to communicate.

I've tried to connect the Postgresql from CLI which is working but its not allowing me to connect the same from odoo web level. Is there any other configuration where we have to mentioned the postgres port and host information apart from conf file.

**Comment by andresbono** [comment]
Hi @kathpalrk, did you specify the `POSTGRESQL_PORT_NUMBER` environment variable when you first executed the container? How are you deploying the container?
