### ISSUE TITLE
Connecting to Bitnami PostgresHA

### ISSUE THREAD

**Issue by tundraerp** [bitnami/bitnami-docker-odoo#81]
I'm running Rancher 2.3.5 and K8 cluster 1.17.2. I've installed postgres-ha no problem. I'm trying to point my Odoo chart to the pgpool node. It stalls at:
```
ubuntu@ip-172-31-17-176:~/kubectl$ kubectl logs odoo-7c5b9b678c-m7zkm -n neg-ec

Welcome to the Bitnami odoo container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-odoo
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-odoo/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing odoo
odoo    INFO  Configuring Odoo database...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql-ha-neg-ec-pgpool.neg-ec.svc.cluster.local:5432
postgre INFO  PostgreSQL server listening and working at postgresql-ha-neg-ec-pgpool.neg-ec.svc.cluster.local:5432
odoo    INFO  Preparing Odoo environment...
```

Here are the Odoo chart (13.1) parameters I'm sending:
```
odooUsername=admin
odooPassword=gppRp86SDK
ingress.hosts[0].name=neg.ec
ingress.hosts[0].tls=true
ingress.hosts[0].certManager=true
ingress.hosts[0].tlsSecret=neg-ec-prod
persistence.storageClass=openebs-cstor-disk
postgresql.enabled=false
externalDatabase.host=postgresql-ha-neg-ec-pgpool.neg-ec.svc.cluster.local
externalDatabase.user=postgres
externalDatabase.password=yatI9wDkKr
```
However, I am getting a warning when I check the events during K8 deployment of the Odoo chart:
```
Warning | Unhealthy | Readiness probe failed: Get http://10.42.0.30:8069/: dial tcp 10.42.0.30:8069: connect: connection refused | 3 minutes ago
```
btw: I tried extra long Readiness probe / Liveliness probe values with no luck.

I can't seem to find any deeper logs on what's going on, any help appreciated...

**Comment by tundraerp** [comment]
I noticed a version bump to 13.02 overnight but still same issue as above.

**Comment by juan131** [comment]
Hi @tundraerp 

The Bitnami Odoo chart is meant to be used with the [Bitnami PostgreSQL chart](https://github.com/bitnami/charts/tree/master/upstreamed/postgresql) (instead of the PostgreSQL HA one). However, that shouldn't be an issue since you're using it as a "external" database.

Let's try to increase the verbosity in the logs of Odoo container so we can obtain more information about what's going on.

Could you edit the Odoo deployment using the command below?

```bash
$ kubectl edit deployment odoo
```

You'll have to apply the changes below:

```diff
     spec:
       containers:
       - env:
+        - name: NAMI_DEBUG
+          value: "--log-level trace"
         - name: POSTGRESQL_HOST
           value: odoo-postgresql
         - name: POSTGRESQL_USER
           value: postgres
```

**Comment by tundraerp** [comment]
Looks like it's all good from the Bitnami side - it's just waiting for container to be ready.
```
nami    INFO  Initializing odoo
odoo    DEBUG Creating Odoo system user...
odoo    INFO  Configuring Odoo database...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at odoo-1582818113-postgresql:5432
postgre TRACE [canConnect] Testing connection with 'postgres' user
postgre TRACE [showDatabases] Getting databases for 'postgres' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hodoo-1582818113-postgresql,-dpostgres,-Upostgres,-cSELECT datname FROM pg_database;
postgre TRACE [showDatabases] Databases: " postgres\n template1\n template0\n\n"
postgre TRACE [canConnect] Connection with 'postgres' user is successful
postgre INFO  PostgreSQL server listening and working at odoo-1582818113-postgresql:5432
odoo    INFO  Preparing Odoo environment...
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hodoo-1582818113-postgresql,-dpostgres,-Upostgres,-cSELECT 1 FROM pg_roles WHERE rolname='bn_odoo'
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hodoo-1582818113-postgresql,-dpostgres,-Upostgres,-cCREATE USER "bn_odoo" PASSWORD 'kQR9v6sq' CREATEDB
odoo    TRACE [configurePermissions] File to chown: /opt/bitnami/odoo

```
I think it's a K8 / Rancher network thing. It's like Odoo isn't listening on the 8069 port. (or it could be that 127.0.0.1 vs 0.0.0.0 access issue).

I'm also running the plain vanilla stable/odoo chart and not using an external db. Postgres comes up fine.

**Comment by tundraerp** [comment]
OK, I set a crazy long livenessProbe (3000) and it's coming up. Looks like Odoo wasn't up yet before it got probed.

**Comment by marcosbc** [comment]
@tundraerp AFAIK the current default is 10 minute, which should be more than enough. It would make sense to be a networking issue.

In any case, and just to clarify, did it work for you after increasing the livenessProbe?

**Comment by tundraerp** [comment]
yes, no problems now.

**Comment by juan131** [comment]
Great!! I'm glad you were able to solve it after increasing the timeout of the probes. I proceed to close the issue, but please feel free to reopen it if you require further help

**Comment by tundraerp** [comment]
Quick question - when connecting to an external database do I need the bitnami_odoo init database present? (or is it created during installation). I have a clean install connecting to an external postgresql-ha cluster and it just sits there and eventually times out when installing on my cluster.
```
ReplicaSet "odoo-neg-ec-fb4fc7776" has timed out progressing.; Deployment does not have minimum availability.
```

**Comment by juan131** [comment]
Hi @tundraerp 

It will try to create it since it assumes the credentials you're passing to Odoo are the one for the "postgres" (admin) user of the PostgreSQL server.

>  I have a clean install connecting to an external postgresql-ha cluster and it just sits there and eventually times out when installing on my cluster

What logs can you see in the Odoo container?

**Comment by tundraerp** [comment]
Thanks - yes we're using the postgres (admin) login. It's finds and connects to the postgres-ha cluster no problem. Then it stalls while creating Odoo environment. Basically the same description of the pod earlier up above. We've decided to stick with local postgres instance that's built into the chart for now until we can get this sorted.

**Comment by juan131** [comment]
> It's finds and connects to the postgres-ha cluster no problem. Then it stalls while creating Odoo environment.

Could you please share the complete logs @tundraerp ?
