### ISSUE TITLE
Can’t Find path file location odoo on linux 

### ISSUE THREAD

**Issue by steve-gil** [bitnami/bitnami-docker-odoo#83]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

I want to look for the odoo source code file but it's not found in the following folder / opt / bitnami / nginx /
![image](https://user-images.githubusercontent.com/8042532/77025947-01ecee80-69c5-11ea-84e0-adbeeda38c69.png)

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.1
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 2
  Paused: 0
  Stopped: 3
 Images: 5
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-88-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.852GiB
 Name: CQVMERPODOO
 ID: OFYG:DKBZ:QLWX:47ZG:75H7:5MYY:OJ2D:5NGD:NTMU:OOPI:RJ4M:TFA5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by Mauraza** [comment]
Hello @steve-gil,

I am sorry but the Odoo container doesn't use Nginx, but if you run an Odoo container the path is `/opt/bitnami/odoo`.

**Comment by steve-gil** [comment]
> Hello @steve-gil,
> 
> I am sorry but the Odoo container doesn't use Nginx, but if you run an Odoo container the path is `/opt/bitnami/odoo`.

I not find on this path "/opt/bitnami/odoo 
![image](https://user-images.githubusercontent.com/8042532/78471282-567cc180-775a-11ea-88fb-9a71ca997834.png)

**Comment by Mauraza** [comment]
Hi @steve-gil,

In Odoo don't have a lestscrypt,  after you run `docker-compose up -d`  with this file https://github.com/bitnami/bitnami-docker-odoo/blob/master/docker-compose.yml you can do `docker exec -ti your-odoo-container bash`  
```
root@2bad7941d80b:/# ls /opt/bitnami/
base  common  licenses	nami  node  odoo  postgresql  python
```
