### ISSUE TITLE
SOLVED: How to use the odoo server command line of bitnami/odoo13 to uninstall a module

### ISSUE THREAD

**Issue by HarlekinSimplex** [bitnami/bitnami-docker-odoo#85]
**Description**

Once upon a time I did install a module that disabled any options to login.
The uninstallation of that rouge modul was not possible because login was blocked.

The remove that module required two things:
1.) Access to server console 
2.) A proper command to uninstall the modul

Both tasks were quite complex to solve but here is the solution.

**Describe the results you received:**

First I had to understand how I get access to the running odoo container.
That was easy achievable by using docker exec (see below).

Second I had to get access to the server console.
That was tricky to find out.
Bitnami uses a virtual python environment for runningen the odoo server.
You have to activate that environment to run the server manually (see command list below).

Third I had to find out how a module could be safely removed.
Installation and update is easy. Unsinstall quite complex.
I found a solution by triggering the original uninstall event so solve that problem.

Here now the full sequence of statements to remove a modul from a running bitnami/odoo13 container by using command line statements only:

Access to odoo server console using bitnami/odoo13
Uninstall of a module using server console in bitnami/odoo13:

**Run shell to access odoo container:**
`sudo docker exec -it <odoo_container> bash -l`
Replace `<odoo container>` with your actual docker container running odoo.

**Activate virtual python environment:**
`cd /opt/bitnami/odoo && source venv/bin/activate`

**You can run the odoo server manually now as usual by using python:**
`python odoo-server --help`
`python odoo-server --version`

**Removing a module that disabled frontend login:**
**Stop running odoo server using nami:**
`/opt/bitnami/nami/bin/nami stop odoo`

**Trigger uninstall using gui method invoked by using the server shell:**
`echo "self.env['ir.module.module'].search([('name', '=', '<Modul to uninstall>')]).button_immediate_uninstall()" | python odoo-server shell -d <Dateabase> -c ./odoo-server.conf`

Replace `<Database>` with your actual database name.
default database name: bitnami_odoo

Replace `<Modul to uninstall>` with your module to remove.

**After the module was removed restart odoo server using nami again:**
`/opt/bitnami/nami/bin/nami start odoo`

**Deactivate virtual python environment if you like:**
`deactivate`

**Exit container:**
`exit`

Enjoy your successful removal and your regained full access to the odoo server command line.
;-)
Cheers
Stephan

**Comment by dani8art** [comment]
Hi @HarlekinSimplex , very good explanation, and great contribution, thank you so much!

**Comment by HarlekinSimplex** [comment]
Some more ideas to do the uninstall.

Maybe a even more usefull and versatile way to access any odoo server.
Just use **xmlrpc** for that.

The is a nice tool called odooly that already replaced the older erppeek tool to do just that very easyly.

Project Documentaion is here:
[https://pypi.org/project/Odooly/](https://pypi.org/project/Odooly/)

With that you can connect to any odoo server and send queries for data retrival or function calls to it.
In particular you can send the same function call I have posted above using this tool to your server without digging deep into the container to access the server console itself.
Just connect to the server using its url retrieve, find the module to remove and call its uninstall method.
Simple as that.
No hassel with venv or other issues that come with accessing the server natively.

**First you need odooly:**
`pip install odooly`

**Create an odooly config file:**
For convenience of use, just prepare a odooly.ini config file with all the relevant environment data.
You can pass all your environment information using commandling arguments as well.
But if you have different environment for dev, test and production for example, using odooly.ini makes usage way esasier.
Odooly expects the odooly.ini file in the current directory if no other path is specifed using `-c <conig_file>`.

```
[DEFAULT]
scheme = http
host = localhost
port = 80
database = bitnami_odoo
username = admin
password = admin
protocol = xmlrpc

[dev]
scheme = http
host = <your dev server>
port = <your dev port>
database = <your dev deb>
username = <your dev odoo user to connect with>
password = <your dev odoo user password to connect with>
protocol = xmlrpc

[test]
...

[prod]
...
```

There are other connect modes possible as well.
See odooly documentation (see link above).

```
[dev_jsonrpc]
username = ...
password = ...
protocol = jsonrpc

[local]
scheme = local
```

**You can query odooly what environemts are configured:**
`odooly --list`

**Now openn odooly in interactiv mode with your target environment connected:**
`odooly --env dev`

**Query the module to uninstall from the database:**
`module = env['ir.module.module'].search([('name', '=', '<Module to uninstall>')])`

**And call the uninstall mathod of the module:**
`module.button_immediate_uninstall()`

**You can of course put that in one line if you like:**
`env['ir.module.module'].search([('name', '=', '<Module to uninstall>')]).module.button_immediate_**uninstall()**`

**And of course you can install modules the same way just calling the install method:**
`env['ir.module.module'].search([('name', '=', '<Module to install>')]).module.button_immediate_**install()**`

Essentially this apprach is identical to the one useing the odoo server shell directly.
But with odooly you can manage module installations easly **remotely** with scripts.
Deploying/managing different odoo installation gets very easy with that.
Beeing able to remove malicious modules that kill web login entirely, is just a welcome additional option here.

Hope that helps.

Enjoy
Cheers Stephan
