### ISSUE TITLE
"Error executing postInstallation: The search took more than 180 seconds"

### ISSUE THREAD

**Issue by isaac1304** [bitnami/bitnami-docker-odoo#88]
**Description**

**Steps to reproduce the issue:**

1. Deploy an PostgreSQL instance in my K8 cluster. (docker.io/bitnami/postgresql:11-debian-10)
2. Deploy an Odoo container into my k8 cluster. (docker.io/bitnami/odoo)

**Describe the results you received:**

--During the installation of Odoo I received a message "Error executing postInstallation: The search took more than 180 seconds"
<img width="760" alt="image" src="https://user-images.githubusercontent.com/7354207/86436759-1dec7580-bcc0-11ea-957b-9b7b07a37d30.png">

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
DigitalOcean Kubernetes Cluster.

**Comment by miguelaeh** [comment]
Hi @isaac1304 ,
It seems to be an issue related to the Odoo modules. Are you using custom images?
Also, I would like to recommend you to use our Odoo Helm Chart, using it you can forget about the connectivity and any other configuration stuff: https://github.com/bitnami/charts/tree/master/bitnami/odoo

**Comment by isaac1304** [comment]
Helio Miguel! thank you for your reply.

I already tried with that chart, but it is less configurable than use the image bitnami/odoo. For example, when I tried to change the resources and credentials (Like in the below example), the chart never come up, just when I use the default configuration, and I want to configure the deployment a little, for learning purpose.

`helm install techbox-1 --set odooUsername=isaac@granados.cr,odooEmail=isaac@granados.cr,odooUsername=isaac@granados.cr,odooPassword=<xxxxxxx>,resources.requests.memory=768Mi,resources.requests.cpu=450m,postgres.postgresqlPassword=" " bitnami/odoo`

Do you suggest another way to deploy the images to avoid this issue?

**Comment by miguelaeh** [comment]
Hi @isaac1304 ,
Coudl you share the error you are getting with the helm chart? I used the command you posted changing the password an it worked fine:
```
helm install techbox-1 --set odooUsername=isaac@granados.cr,odooEmail=isaac@granados.cr,odooUsername=isaac@granados.cr,odooPassword=password,resources.requests.memory=768Mi,resources.requests.cpu=450m,postgres.postgresqlPassword=password bitnami/odoo
```

And getting the pods:
```
techbox-1-odoo-65d7cdccd7-hclc7                     1/1     Running                 0          6m7s
techbox-1-postgresql-0                              1/1     Running                 0          6m7s
```

**Comment by isaac1304** [comment]
> Hi @isaac1304 ,
> 
> Could you share the error you are getting with the helm chart? I used the command you posted changing the password and it worked fine:
> 
> ```
> 
> helm install techbox-1 --set odooUsername=isaac@granados.cr,odooEmail=isaac@granados.cr,odooUsername=isaac@granados.cr,odooPassword=password,resources.requests.memory=768Mi,resources.requests.cpu=450m,postgres.postgresqlPassword=password bitnami/odoo
> 
> ```
> 
> 
> 
> And getting the pods:
> 
> ```
> 
> techbox-1-odoo-65d7cdccd7-hclc7                     1/1     Running                 0          6m7s
> 
> techbox-1-postgresql-0                              1/1     Running                 0          6m7s
> 
> ```

I think it was an internal error with helm... but it is resolve now! I have both pods up, now I have another problem with SSL certificates 😅, but that is another story. Thank you for check! In my own deployment I just added LivenessProbe section and it’s works! In case someone help it.

**Comment by miguelaeh** [comment]
I am glad it is working now @isaac1304 ,
Don't hesitate to ask again if you find any issues!!
Reagards.
