### ISSUE TITLE
Odoo failing initialization in k8s cluster

### ISSUE THREAD

**Issue by andresbono** [bitnami/bitnami-docker-odoo#89]
Hello @andresbono! I am trying to install Odoo using docker images, into a Kubernetes cluster... Seems like all is working fine but I am getting this error when try to install the Odoo:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/7354207/86436336-4de74900-bcbf-11ea-91d9-3f979ba8cc2d.png">
 Any idea about how to avoid this problem? I tried the installation with helm, but it is less configurable.

_Originally posted by @isaac1304 in https://github.com/bitnami/bitnami-docker-odoo/issues/55#issuecomment-653366143_

**Comment by andresbono** [comment]
Hi @isaac1304, the way we recommend and test deployments of Odoo in Kubernetes clusters is using our helm chart: https://github.com/bitnami/charts/tree/master/bitnami/odoo. If you still want to maintain your own k8s manifests, you may find useful executing `helm template bitnami/odoo` and compare the output with the files that you have.

You can also try to exec into the odoo container and see what is going on in `/opt/bitnami/odoo/logs/odoo-server.log`. You might find some error message that might lead you into the right direction.

**Comment by isaac1304** [comment]
Hello Andres, I already tried with that chart, but when I tried to change things las resources (cpu, memory) and access credentials, the deployment never come up (helm install techbox-1 --set odooUsername=isaac@granados.cr,odooEmail=isaac@granados.cr,odooUsername=isaac@granados.cr,odooPassword=13Abril93,resources.requests.memory=768Mi,resources.requests.cpu=450m,postgres.postgresqlPassword=" " bitnami/odoo)

**Comment by isaac1304** [comment]
Hello Andres, I already tried with that chart, but when I tried to change things las resources (cpu, memory) and access credentials, the deployment never come up, like this: (helm install techbox-1 --set odooUsername=isaac@granados.cr,odooEmail=isaac@granados.cr,odooUsername=isaac@granados.cr,odooPassword=13Abril93,resources.requests.memory=768Mi,resources.requests.cpu=450m,postgres.postgresqlPassword=" " bitnami/odoo)


That is the reason why I decided create my own deploy using bitíami/odoo image.
I will try with that a approach you suggested, thank you so much for your time! :)

**Comment by andresbono** [comment]
Great, @isaac1304. Let us know if you need further help.

**Comment by isaac1304** [comment]
I just added the LivenessProbe section from that chart and all is working! Thank you @andresbono !, I think we can close the issue.

**Comment by andresbono** [comment]
Great! :tada: Good to know!
