### ISSUE TITLE
change default postgres dbname with env_var ? 

### ISSUE THREAD

**Issue by jCOTINEAU** [bitnami/bitnami-docker-odoo#95]
Hello everyone.

**Description**

is there a way to change the default **postgres** db_name ?

i am using a cloud database ( OVH ) that does not allow **postgres** to be a dbName.

I've found on the odoo helm bitnami chart that the parameter **externalDatabase.database** exist, but it is not used in the template.

And in your Dockerfile it seems there is no db_name env.

Am i able to mount an odoo.conf file in order to fix this behaviour ? 

Thanks a lot for your help.
Best Regards.

**Comment by rafariossaa** [comment]
Hi,
  The database that is created is called `bitnami_odoo`:
```
I have no name!@19c3fa75678b:/$ psql
psql (11.11)
Type "help" for help.

postgres=# \l
                                   List of databases
     Name     |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
--------------+----------+----------+-------------+-------------+-----------------------
 bitnami_odoo | bn_odoo  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
              |          |          |             |             | postgres=CTc/postgres
 template1    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
              |          |          |             |             | postgres=CTc/postgres
(4 rows)

postgres=# 
```
  Maybe you mean the hostname of the server of the postgresql, in that case you can change configure it with `POSTGRESQL_HOST`. You can check the environment variables [here](https://github.com/bitnami/bitnami-docker-odoo#user-content-environment-variables).

**Comment by jCOTINEAU** [comment]
Hum that's strange in my db log i had something like unauthorized operation on db **postgres** with no sign at all of a db named bitnami_odoo.

Could this be because of the way the chart try to create the database itself and therefore has no right to do it ?

**Comment by rafariossaa** [comment]
Hi,
  Could you clean it all and deploy again from scratch to get the full log ?
  If it is not able to create the database, it should have failed and just stopped. Maybe there is a bug and that could happened, but I would like to see the log. Please, I you redeploy it enable debug by setting `BITNAMI_DEBUG=true`.

 > I feel like i am not under-stable enough, i am sorry english is not my first language.
Don't worry, english is neither my mother language :wink: . If something is not clear for me I will ask for further clarification.
