### ISSUE TITLE
Setting the initial user password should be done through the bn_odoo user - not the initial user 

### ISSUE THREAD

**Issue by fhossfel** [bitnami/bitnami-docker-odoo#98]
Post initial installation the user initial user password ist set with the following update statement:

`postgre TRACE [execute] Executing psql with parameters -t,-p5432,-h35.240.94.117,-dbitnami_odoo,-Upostgres,-cUPDATE res_users SET password='MyInitialPassword' WHERE id='2'`

By providing the option "-Upostgres" specifies that the provided dab account that is used to create the bn_odoo user is used for the update. However, it is possible that the initial user has the permissions to create user ("CREATE ROLE") but is not a superuser and hence does not have the permission to access the tables in the bitnami_odoo database. This is the case for Google Cloud SQL instances but may also be the case in other setups.

The installation will fail with

`Error executing 'postInstallation': ERROR:  permission denied for table res_users

nami    TRACE Error: Error executing 'postInstallation': ERROR:  permission denied for table res_users`

I think a proper fix would be to use the bn_odoo user to access the database.

I was not able to find the statement in the source code so I am not actually able to fix the issue. But could somebody change this to use the bn_user?

**Comment by marcosbc** [comment]
Hi @fhossfel, we just released `12.0.20210615-debian-10-r20`/`13.0.20210610-debian-10-r24`/`14.0.20210610-debian-10-r22` versions of this container which includes a major refactor of the existing logic.

Now, the entire installation logic is performed with the `bn_odoo` user. Let us know if you continue to find issues.
