### ISSUE TITLE
Odoo: Wrong ownership of created database when specifying POSTGRESQL_CLIENT_POSTGRES_USER/PASSWORD

### ISSUE THREAD

**Issue by fhossfel** [bitnami/bitnami-docker-odoo#99]
I am trying out the Odoo chart (Thanks! Much appreciated!) but there is still a bug when creating a database. The database will be owned by the Postgres user not the bn_odoo user.

        Name      |        Owner       | Encoding |  Collate   |   Ctype    |            Access privileges   
    --------------+--------------------+----------+------------+------------+-----------------------------------------
     bitnami_odoo | postgres           | UTF8     | en_US.UTF8 | en_US.UTF8 | =Tc/postgres                           +

I think the issue would be trivial by modifying the following line libpostgresqlclient.sh:

` "${postgresql_execute_cmd[@]}" "${postgresql_execute_flags[@]}" <<EOF
SELECT 'CREATE DATABASE "${database}"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${database}')\gexec`

by adding `WITH owner=${POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME}` but I am not 100% sure what the side effects are if one is not creating the DB so I don't really feel qualified to provide a patch.

**Comment by miguelaeh** [comment]
Hi @fhossfel ,
Could you share the logs or the errors this is causing?

**Comment by fhossfel** [comment]
Sure:

    odoo 10:36:58.37 
    odoo 10:36:58.37 Welcome to the Bitnami odoo container    
    odoo 10:36:58.37 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-odoo
    odoo 10:36:58.38 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-odoo/issues
    odoo 10:36:58.38 
    odoo 10:36:58.39 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
    odoo 10:36:58.40 INFO  ==> Trying to connect to the database server
    odoo 10:36:58.43 INFO  ==> Creating database user bn_odoo
    odoo 10:36:58.47 INFO  ==> Creating database bitnami_odoo
    odoo 10:36:58.57 INFO  ==> Ensuring Odoo directories exist
    odoo 10:36:58.59 INFO  ==> Trying to connect to the database server
    odoo 10:36:58.61 INFO  ==> Validating database owner
    odoo 10:36:58.65 ERROR ==> The database 'bitnami_odoo' is not owned by database user 'bn_odoo'. This is required for the Odoo application to be able to use this database.

I am running this with the following settings:

    BITNAMI_DEBUG:                               false
    ALLOW_EMPTY_PASSWORD:                        no
    ODOO_DATABASE_HOST:                          35.240.94.117
    ODOO_DATABASE_PORT_NUMBER:                   5432
    ODOO_DATABASE_NAME:                          bitnami_odoo
    ODOO_DATABASE_USER:                          bn_odoo
    ODOO_DATABASE_PASSWORD:                      <set to the key 'postgresql-password' in secret 'odoo-hap-externaldb'>  Optional: false
    POSTGRESQL_CLIENT_DATABASE_HOST:             35.240.94.117
    POSTGRESQL_CLIENT_DATABASE_PORT_NUMBER:      5432
    POSTGRESQL_CLIENT_POSTGRES_USER:             postgres
    POSTGRESQL_CLIENT_POSTGRES_PASSWORD:         <set to the key 'postgresql-postgres-password' in secret 'odoo-hap-externaldb'>  Optional: false
    POSTGRESQL_CLIENT_CREATE_DATABASE_NAME:      bitnami_odoo
    POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME:  bn_odoo
    POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD:  <set to the key 'postgresql-password' in secret 'odoo-hap-externaldb'>  Optional: false
    ODOO_EMAIL:                                  felix.hossfeld@thoughtgang.de
    ODOO_PASSWORD:                               <set to the key 'odoo-password' in secret 'odoo-hap'>  Optional: false
    ODOO_SKIP_BOOTSTRAP:                         
    ODOO_LOAD_DEMO_DATA:                         no
    NAMI_DEBUG:                                  --log-level=trace8

**Comment by fhossfel** [comment]
Okay, with BITNAMI_DEBUG enabled the log is much more helpful:

    odoo 10:45:27.36 
    odoo 10:45:27.36 Welcome to the Bitnami odoo container
    odoo 10:45:27.37 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-odoo
    odoo 10:45:27.37 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-odoo/issues
    odoo 10:45:27.37 
    odoo 10:45:27.38 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
    odoo 10:45:27.39 INFO  ==> Trying to connect to the database server
    odoo 10:45:27.39 DEBUG ==> Executing SQL command:
    SELECT 1
     ?column? 
    ----------
            1
    (1 row)
    
    odoo 10:45:27.43 INFO  ==> Creating database user bn_odoo
    odoo 10:45:27.43 DEBUG ==> Executing SQL command:
    DO
    $do$
    BEGIN
       IF NOT EXISTS (
          SELECT FROM pg_catalog.pg_roles WHERE rolname = 'bn_odoo'
       ) THEN
          CREATE ROLE "bn_odoo" LOGIN PASSWORD 'sDxfpy0lcwIq5ump';
       END IF;
    END
    $do$;
    DO
    odoo 10:45:27.47 INFO  ==> Creating database bitnami_odoo
    odoo 10:45:27.47 DEBUG ==> Executing SQL command:
    SELECT 'CREATE DATABASE "bitnami_odoo"'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'bitnami_odoo')\gexec
    odoo 10:45:27.50 DEBUG ==> Providing privileges to username bn_odoo on database bitnami_odoo
    odoo 10:45:27.50 DEBUG ==> Executing SQL command:
    GRANT ALL PRIVILEGES ON DATABASE "bitnami_odoo" TO "bn_odoo";
    ALTER DATABASE "bitnami_odoo" OWNER TO "bn_odoo";
    GRANT
    ERROR:  must be member of role "bn_odoo"
    odoo 10:45:27.57 DEBUG ==> Validating settings in ODOO_* environment variables...
    odoo 10:45:27.58 INFO  ==> Ensuring Odoo directories exist
    odoo 10:45:27.59 INFO  ==> Trying to connect to the database server
    odoo 10:45:27.59 DEBUG ==> Executing SQL command:
    SELECT 1
     ?column? 
    ----------
            1
    (1 row)
    
    odoo 10:45:27.63 INFO  ==> Validating database owner
    odoo 10:45:27.64 DEBUG ==> Executing SQL command:
    SELECT u.usename FROM pg_database d JOIN pg_user u ON (d.datdba = u.usesysid) WHERE d.datname = 'bitnami_odoo' AND u.usename = 'bn_odoo';
    odoo 10:45:27.67 ERROR ==> The database 'bitnami_odoo' is not owned by database user 'bn_odoo'. This is required for the Odoo application to be able to use this database.`

So it creates the database as the `postgres` user and then tries to gift it to `bn_odoo`. This does not work because postgres is not member of the role `bn_odoo` and is not supposed to be. This means that the `WITH owner=bn_odoo` will probably fail for the same reason. The only way to do this is to use the bn_odoo user to create the database - which is what the frontend database manager does anyway.

**Comment by miguelaeh** [comment]
Hi @fhossfel ,
I tried to reproduce the issue without luck.
Could you give a try to delete the PVC of PostgreSQL? Just in case it is getting an old database with the wrong configuration. Note that you shouldn't do that in case you have production data there.

**Comment by fhossfel** [comment]
Sorry, I forgot to mention that I am on Google Cloud SQL.

             Role name         |                         Attributes                         |      Member of      
    ---------------------------+------------------------------------------------------------+---------------------
     postgres                  | Create role, Create DB                                     | {cloudsqlsuperuser}


The postgres user has not superuser permission.If you want to simulate this you have to create a postgres2 user with Create role and Create DB privileges.

**Comment by miguelaeh** [comment]
Hi @fhossfel ,
If you change `ODOO_DATABASE_USER` to set `postgres` instead of `bn_odoo` does it work?
Since postgres owns the database the message:
> The database 'bitnami_odoo' is not owned by database user 'bn_odoo'

should not appear

**Comment by fhossfel** [comment]
Well, not really. I use the helm chart and it would need to be updated to allow for that.

I think there wiped need to Abe an option to not create the user/database when using an external db.

Hoover, I still think that using the Odoo user to create the db is the right thing to to(tm).

I can provide a patch but I do not have sufficient alternatives - especially outside of k8n - to test this.

**Comment by miguelaeh** [comment]
Hi @fhossfel ,
>I use the helm chart and it would need to be updated to allow for that.

The chart already supports that option at https://github.com/bitnami/charts/blob/3fbdfc5aa6abce3e9f65d0009f08821583f64e84/bitnami/odoo/values.yaml#L620

>  think there wiped need to Abe an option to not create the user/database when using an external db.

The Odoo image also have a `ODOO_SKIP_BOOTSTRAP` variable that allows to do that, but I just checked and the user change is always done even setting that variable.
